"""Pair fusion index: reads every @Pair in src/main/java/dev/wildercord/pairs and writes the dispatch.

  python tools/pairs/index.py            check every pair, then rewrite the generated index
  python tools/pairs/index.py --check    only check (exit 1 on any problem)
  python tools/pairs/index.py --file F   only check one file, against everything already written
  python tools/pairs/index.py --stats    how many pairs are written

A pair is a public static void method taking one PairCast, right under an annotation:

  @Pair(a = "chill", b = "shock", name = "Frostwire", element = "storm", kind = EffectKind.HARMFUL,
      traits = {"power", "radius"}, text = "What its rune says it does.")

a < b (rune paths, alphabetically), both in tools/pairs/runes.tsv; element is one of their two elements.
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
PAIRS = os.path.join(ROOT, "src", "main", "java", "dev", "wildercord", "pairs")
GEN = os.path.join(PAIRS, "gen")
KINDS = {"HELPFUL", "HARMFUL", "WORLD", "MOVEMENT"}
TRAITS = {"power", "duration", "radius", "linger"}
NL = "\n"
STRING = re.compile(r'"(?:[^"\\]|\\.)*"')
GENERATED = "// Generated by tools/pairs/index.py from the @Pair methods: do not edit.\n"


def runes():
    out = {}
    with open(os.path.join(HERE, "runes.tsv"), encoding="utf-8") as f:
        for line in f:
            if line.startswith("#") or not line.strip():
                continue
            r = line.rstrip("\n").split("\t")
            out[r[0]] = {"element": r[1], "name": r[6]}
    return out


def annotation_body(src, start):
    """The text inside @Pair( ... ), from just after its parenthesis, and where it ends."""
    i, depth = start, 1
    while i < len(src):
        c = src[i]
        if c == '"':
            m = STRING.match(src, i)
            if not m:
                return None, i
            i = m.end()
            continue
        if c == "(":
            depth += 1
        elif c == ")":
            depth -= 1
            if depth == 0:
                return src[start:i], i + 1
        i += 1
    return None, i


def split_fields(body):
    parts, depth, cur, j = [], 0, "", 0
    while j < len(body):
        c = body[j]
        if c == '"':
            m = STRING.match(body, j)
            cur += m.group(0)
            j = m.end()
            continue
        if c in "{(":
            depth += 1
        elif c in "})":
            depth -= 1
        if c == "," and depth == 0:
            parts.append(cur)
            cur = ""
        else:
            cur += c
        j += 1
    if cur.strip():
        parts.append(cur)
    fields = {}
    for p in parts:
        if "=" not in p:
            raise ValueError("expected key = value, got: " + p.strip()[:60])
        k, v = p.split("=", 1)
        fields[k.strip()] = v.strip()
    return fields


def literal(v):
    """A string value (several literals joined with + allowed), as the inside of one Java literal."""
    lits = STRING.findall(v)
    rest = STRING.sub("", v).replace("+", "").strip()
    if not lits or rest:
        raise ValueError("expected a string literal, got: " + v[:60])
    return "".join(l[1:-1] for l in lits)


METHOD = re.compile(r"\s*(?:/\*\*.*?\*/\s*)?public\s+static\s+void\s+(\w+)\s*\(\s*PairCast\s+\w+\s*\)", re.S)


def parse(path, known, problems):
    with open(path, encoding="utf-8") as f:
        src = f.read()
    rel = os.path.relpath(path, ROOT).replace(os.sep, "/")
    pkg = re.search(r"^package\s+([\w.]+)\s*;", src, re.M)
    cls = os.path.splitext(os.path.basename(path))[0]
    if not pkg:
        problems.append(f"{rel}: no package line")
        return []
    if not re.search(r"public\s+final\s+class\s+" + re.escape(cls) + r"\b", src):
        problems.append(f"{rel}: the class must be 'public final class {cls}'")
    out = []
    for m in re.finditer(r"@Pair\s*\(", src):
        where = f"{rel}:{src.count(NL, 0, m.start()) + 1}"
        body, end = annotation_body(src, m.end())
        if body is None:
            problems.append(f"{where}: unclosed @Pair(")
            continue
        method = METHOD.match(src, end)
        if not method:
            problems.append(f"{where}: @Pair must sit right on 'public static void name(PairCast c)'")
            continue
        try:
            f = split_fields(body)
            e = {
                "a": literal(f["a"]), "b": literal(f["b"]), "name": literal(f["name"]), "element": literal(f["element"]),
                "kind": f["kind"].replace("EffectKind.", "").strip(), "text": literal(f["text"]),
                "traits": [literal(t) for t in STRING.findall(f.get("traits", "{}"))],
                "pkg": pkg.group(1), "cls": cls, "method": method.group(1), "where": where,
            }
        except (KeyError, ValueError) as err:
            problems.append(f"{where}: {err}")
            continue
        a, b = e["a"], e["b"]
        if a not in known:
            problems.append(f"{where}: no pairable rune '{a}'")
        if b not in known:
            problems.append(f"{where}: no pairable rune '{b}'")
        if a >= b:
            problems.append(f"{where}: a must come before b alphabetically ('{a}' / '{b}')")
        if a in known and b in known and e["element"] not in (known[a]["element"], known[b]["element"]):
            problems.append(f"{where}: element '{e['element']}' is neither {a}'s ({known[a]['element']}) nor {b}'s ({known[b]['element']})")
        if e["kind"] not in KINDS:
            problems.append(f"{where}: kind must be one of {sorted(KINDS)}")
        bad = [t for t in e["traits"] if t not in TRAITS]
        if bad:
            problems.append(f"{where}: unknown traits {bad} (use {sorted(TRAITS)})")
        if not (1 <= len(e["name"]) <= 32):
            problems.append(f"{where}: name must be 1-32 characters")
        if not (20 <= len(e["text"]) <= 320):
            problems.append(f"{where}: text must be 20-320 characters (it is {len(e['text'])})")
        out.append(e)
    return out


def all_files():
    out = []
    gen = os.path.abspath(GEN)
    for d, _, names in os.walk(PAIRS):
        if os.path.abspath(d).startswith(gen):
            continue
        for n in names:
            if n.endswith(".java") and n not in ("Pair.java", "PairIndex.java", "PairSpecs.java"):
                out.append(os.path.join(d, n))
    return sorted(out)


def collect(files, problems):
    known = runes()
    entries = []
    for path in files:
        entries.extend(parse(path, known, problems))
    return entries


def cross_check(entries, problems):
    pairs, names = {}, {}
    for e in entries:
        k = (e["a"], e["b"])
        if k in pairs:
            problems.append(f"{e['where']}: the pair {k[0]} / {k[1]} is already written at {pairs[k]}")
        pairs.setdefault(k, e["where"])
        n = e["name"].lower()
        if n in names:
            problems.append(f"{e['where']}: the name \"{e['name']}\" is already used at {names[n]}")
        names.setdefault(n, e["where"])


def write(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    old = open(path, encoding="utf-8").read() if os.path.exists(path) else None
    if old != text:
        with open(path, "w", encoding="utf-8", newline="\n") as f:
            f.write(text)


def generate(entries):
    by_a = {}
    for e in entries:
        by_a.setdefault(e["a"], []).append(e)
    keep = set()
    for a, es in sorted(by_a.items()):
        es.sort(key=lambda e: e["b"])
        s_name, c_name = "S_" + a, "C_" + a
        specs = [f'\t\t\tcase "{e["b"]}" -> new PairSpec("{e["name"]}", "{e["element"]}", EffectKind.{e["kind"]}, "{e["text"]}"'
                 + "".join(f', "{t}"' for t in e["traits"]) + ");" for e in es]
        casts = [f'\t\t\tcase "{e["b"]}" -> {e["pkg"]}.{e["cls"]}.{e["method"]}(c);' for e in es]
        write(os.path.join(GEN, s_name + ".java"),
              GENERATED + "package dev.wildercord.pairs.gen;\n\nimport dev.wildercord.spell.EffectKind;\nimport dev.wildercord.spell.PairSpec;\n\n"
              f"public final class {s_name} {{\n\tprivate {s_name}() {{}}\n\n\tpublic static PairSpec spec(String b) {{\n\t\treturn switch (b) {{\n"
              + NL.join(specs) + "\n\t\t\tdefault -> null;\n\t\t};\n\t}\n}\n")
        write(os.path.join(GEN, c_name + ".java"),
              GENERATED + "package dev.wildercord.pairs.gen;\n\nimport dev.wildercord.cast.PairCast;\n\n"
              f"public final class {c_name} {{\n\tprivate {c_name}() {{}}\n\n\tpublic static boolean cast(String b, PairCast c) {{\n\t\tswitch (b) {{\n"
              + NL.join(casts) + "\n\t\t\tdefault -> {\n\t\t\t\treturn false;\n\t\t\t}\n\t\t}\n\t\treturn true;\n\t}\n}\n")
        keep.update({s_name + ".java", c_name + ".java"})
    if os.path.isdir(GEN):
        for n in os.listdir(GEN):
            if n.endswith(".java") and n not in keep:
                os.remove(os.path.join(GEN, n))
    firsts = sorted(by_a)
    spec_cases = NL.join(f'\t\t\tcase "{a}" -> dev.wildercord.pairs.gen.S_{a}.spec(b);' for a in firsts)
    cast_cases = NL.join(f'\t\t\tcase "{a}" -> dev.wildercord.pairs.gen.C_{a}.cast(b, c);' for a in firsts)
    write(os.path.join(PAIRS, "PairSpecs.java"),
          GENERATED + "package dev.wildercord.pairs;\n\nimport dev.wildercord.spell.PairSpec;\n\n"
          "/** Every written pair's spec, by its two rune paths (alphabetically): null for one not yet written. */\n"
          "public final class PairSpecs {\n\tprivate PairSpecs() {}\n\n\t/** How many pairs are written. */\n"
          f"\tpublic static final int COUNT = {len(entries)};\n\n"
          "\tpublic static PairSpec spec(String a, String b) {\n\t\treturn switch (a) {\n"
          + (spec_cases + NL if spec_cases else "") + "\t\t\tdefault -> null;\n\t\t};\n\t}\n}\n")
    write(os.path.join(PAIRS, "PairIndex.java"),
          GENERATED + "package dev.wildercord.pairs;\n\nimport dev.wildercord.cast.PairCast;\n\n"
          "/** Runs a written pair's effect, by its two rune paths (alphabetically): false for one not yet written. */\n"
          "public final class PairIndex {\n\tprivate PairIndex() {}\n\n"
          "\tpublic static boolean cast(String a, String b, PairCast c) {\n\t\treturn switch (a) {\n"
          + (cast_cases + NL if cast_cases else "") + "\t\t\tdefault -> false;\n\t\t};\n\t}\n}\n")


def main(argv):
    problems = []
    if "--file" in argv:
        files = [os.path.abspath(argv[argv.index("--file") + 1])]
        entries = collect(files, problems)
        others = collect([p for p in all_files() if os.path.abspath(p) not in files], [])
        cross_check(others + entries, problems)
        mine = [os.path.relpath(f, ROOT).replace(os.sep, "/") for f in files]
        problems = [p for p in problems if any(p.startswith(m) for m in mine)]
    else:
        entries = collect(all_files(), problems)
        cross_check(entries, problems)
    if problems:
        print(NL.join(problems))
        print(f"{len(problems)} problem(s)")
        return 1
    if "--stats" in argv:
        known = runes()
        print(f"{len(entries)} pairs written of {len(known) * (len(known) - 1) // 2}")
        return 0
    if "--check" in argv or "--file" in argv:
        print(f"ok: {len(entries)} pair(s)")
        return 0
    generate(entries)
    print(f"index written: {len(entries)} pair(s)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
