package dev.wildercord.wildlife;
import dev.wildercord.cast.feel.Feels;
import net.minecraft.core.BlockPos;
import net.minecraft.network.chat.Component;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.world.item.*;
import net.minecraft.world.phys.*;
import net.minecraft.world.level.ClipContext;
import java.util.*;
/** Fixed player facts, actual material expenditure and no renewable restoration reward. */
public final class DrainhouseInvestigation {
 private DrainhouseInvestigation(){}
 public static final String THRESHOLD="field:drainhouse_threshold",GARDEN="field:drainhouse_garden",ALCOVE="field:drainhouse_alcove",DONE="field:drainhouse_restored";
 private static boolean knows(ServerPlayer p,String k){return FungalInvestigation.knows(p,k);}
 private static boolean admit(ServerPlayer p,BlockPos at){if(!p.level().dimension().equals(net.minecraft.world.level.Level.OVERWORLD) || !p.isAlive() || p.isRemoved() || p.isSpectator() || p.isCreative() || !p.level().hasChunkAt(at) || p.distanceToSqr(Vec3.atCenterOf(at))>16 || !p.level().mayInteract(p,at) || !p.level().getBlockState(at).is(DrainhouseContent.MARK) || !(p.level().getBlockEntity(at) instanceof DrainhouseMarkEntity e) || !e.authentic())return false;var hit=p.level().clip(new ClipContext(p.getEyePosition(),Vec3.atCenterOf(at),ClipContext.Block.COLLIDER,ClipContext.Fluid.NONE,p));return hit.getType()==HitResult.Type.MISS || hit.getBlockPos().equals(at);}
 private static void give(ServerPlayer p,Item item){p.getInventory().placeItemBackInInventory(new ItemStack(item),net.minecraft.util.Prediction.SERVER_ONLY);}
 public static String next(ServerPlayer p){if(!knows(p,FungalInvestigation.FIRST))return "snail";if(!knows(p,THRESHOLD))return "threshold";if(!knows(p,"field:rootmolt_meal"))return "meal";if(!knows(p,GARDEN))return "garden";if(!knows(p,"field:rootmolt_counter"))return "counter";if(!knows(p,ALCOVE))return "alcove";return knows(p,DONE)?"done":"restore";}
 private static void hint(ServerPlayer p){p.sendOverlayMessage(Component.translatable("message.wildercord.drainhouse."+next(p)));}
 public static void read(ServerPlayer p,BlockPos at){if(!admit(p,at)){p.sendOverlayMessage(Component.translatable("message.wildercord.drainhouse.replica"));return;}int kind=p.level().getBlockState(at).getValue(DrainhouseMark.KIND);String flag=kind==0?THRESHOLD:kind==1?GARDEN:ALCOVE;boolean ready=kind==0?knows(p,FungalInvestigation.FIRST):kind==1?knows(p,THRESHOLD) && knows(p,"field:rootmolt_meal"):knows(p,GARDEN) && knows(p,"field:rootmolt_counter");if(ready && FungalInvestigation.remember(p,flag)){give(p,kind==0?DrainhouseContent.ENTRANCE_NOTES:kind==1?DrainhouseContent.GARDEN_NOTES:DrainhouseContent.ALCOVE_NOTES);Feels.sound(p.level(),Vec3.atCenterOf(at),"belowkeeper_read",.45F,1);}hint(p);}
 private static int count(ServerPlayer p,Item item){int n=0;for(int i=0;i<36;i++){var stack=p.getInventory().getItem(i);if(stack.is(item))n+=stack.getCount();}if(p.getOffhandItem().is(item))n+=p.getOffhandItem().getCount();return n;}
 private static void spend(ServerPlayer p,Item item,int amount){for(int i=0;i<36 && amount>0;i++){var stack=p.getInventory().getItem(i);if(stack.is(item)){int debit=Math.min(amount,stack.getCount());stack.shrink(debit);amount-=debit;}}if(amount>0 && p.getOffhandItem().is(item))p.getOffhandItem().shrink(amount);}
 public static boolean restore(ServerPlayer p,BlockPos at){return restore(p,at,(level,pos,state)->level.setBlock(pos,state,3));}
 @FunctionalInterface interface RestorationWriter {boolean set(net.minecraft.server.level.ServerLevel level,BlockPos at,net.minecraft.world.level.block.state.BlockState state);}
 /** Package-local real-writer seam permits deterministic post-world-update admission evidence. */
 static boolean restore(ServerPlayer p,BlockPos at,RestorationWriter writer){if(!admit(p,at) || p.level().getBlockState(at).getValue(DrainhouseMark.KIND)!=2 || !next(p).equals("restore")){hint(p);return false;}if(count(p,SporebackContent.DEW)<2 || count(p,FungalGarden.GILLS)<2 || count(p,Items.COPPER_INGOT)<4){hint(p);return false;}var level=p.level();var ledger=level.getBlockEntity(at);var state=level.getBlockState(at);var restored=state.setValue(DrainhouseMark.RESTORED,true);if(!state.getValue(DrainhouseMark.RESTORED) && !writer.set(level,at,restored))return false;/* A world-update callback can move the player, replace the ledger, spend materials or finish a nested restoration. Re-admit before this payment/reward. */if(p.level()!=level || !admit(p,at) || level.getBlockEntity(at)!=ledger || !level.getBlockState(at).equals(restored) || !next(p).equals("restore") || count(p,SporebackContent.DEW)<2 || count(p,FungalGarden.GILLS)<2 || count(p,Items.COPPER_INGOT)<4)return false;spend(p,SporebackContent.DEW,2);spend(p,FungalGarden.GILLS,2);spend(p,Items.COPPER_INGOT,4);FungalInvestigation.remember(p,DONE);give(p,BelowkeeperEquipment.BELL);Feels.sound(p.level(),Vec3.atCenterOf(at),"belowkeeper_restore",.6F,1);hint(p);return true;}
 public static boolean repair(ServerPlayer p,BlockPos at,ItemStack bell){long now=p.level().getServer().overworld().getGameTime();if(!admit(p,at) || !knows(p,DONE) || p.level().getBlockState(at).getValue(DrainhouseMark.KIND)!=2 || !p.level().getBlockState(at).getValue(DrainhouseMark.RESTORED) || !bell.is(BelowkeeperEquipment.BELL) || (bell!=p.getMainHandItem() && bell!=p.getOffhandItem()) || !bell.isDamaged() || now<p.getAttachedOrElse(DrainhouseContent.REPAIR_READY,0L) || count(p,SporebackContent.DEW)<1 || count(p,FungalGarden.GILLS)<1 || count(p,Items.COPPER_INGOT)<1)return false;spend(p,SporebackContent.DEW,1);spend(p,FungalGarden.GILLS,1);spend(p,Items.COPPER_INGOT,1);bell.setDamageValue(Math.max(0,bell.getDamageValue()-8));p.setAttached(DrainhouseContent.REPAIR_READY,now+1200);Feels.sound(p.level(),Vec3.atCenterOf(at),"belowkeeper_restore",.35F,1.2F);return true;}
}
