package dev.wildercord.player;

import dev.wildercord.spell.Feats;
import dev.wildercord.spell.MasterStudyRules;
import dev.wildercord.spell.Runes;
import net.minecraft.network.chat.Component;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.world.entity.player.Player;

import java.util.ArrayList;
import java.util.List;

/** Lessons survive death and restart in the existing private Grimoire; reading/casting sessions never do. */
public final class MasterStudies {
	private MasterStudies() {}

	public static boolean knowsRelay(Player player) {
		return Heart.discovered(player, MasterStudyRules.RELAY);
	}

	/** A verified copied lesson is retrievable before it is learned; older learned saves remain compatible. */
	public static boolean hasRelayLesson(Player player) {
		return knowsRelay(player) || Heart.discovered(player, MasterStudyRules.RELAY_COPIED);
	}

	public static boolean mayStudyRelay(Player player) {
		return MasterStudyRules.mayStudyRelay(Heart.active(player), Heart.discovered(player, "feat:" + Feats.ARCHIVIST), hasRelayLesson(player));
	}

	public static boolean eligibleRelay(Player player) {
		return MasterStudyRules.eligibleRelay(Heart.active(player), Heart.discovered(player, "feat:" + Feats.ARCHIVIST));
	}

	public static boolean practicedRelay(Player player) {
		return Heart.discovered(player, MasterStudyRules.RELAY_PRACTICE);
	}

	/** Called only by the server's completed, validated Archive reading session. A book item cannot call this. */
	public static boolean learnRelay(ServerPlayer player) {
		if (!player.isAlive() || player.isSpectator() || !mayStudyRelay(player)) return false;
		boolean fresh = remember(player, MasterStudyRules.RELAY);
		Spellbooks.learn(player, Runes.RELAY.id());
		return fresh;
	}

	/** The paid Relay runtime calls this after moving from placement and actually striking a Training Dummy. */
	public static boolean completeRelayPractice(ServerPlayer player) {
		if (!player.isAlive() || !knowsRelay(player) || !eligibleRelay(player)
			|| !remember(player, MasterStudyRules.RELAY_PRACTICE)) return false;
		player.sendSystemMessage(Component.translatable("message.wildercord.relay_lesson.practiced").withColor(0x7FDAD4));
		return true;
	}

	/** A record only: no condensed mana, affinity, XP or combat reward is generated by lesson bookkeeping. */
	public static boolean remember(ServerPlayer player, String key) {
		List<String> entries = Heart.grimoire(player);
		if (entries.contains(key)) return false;
		List<String> next = new ArrayList<>(entries);
		next.add(key);
		player.setAttached(WildercordAttachments.GRIMOIRE, List.copyOf(next));
		return true;
	}
}
