// Generated by tools/pairs/index.py from the @Pair methods: do not edit.
package dev.wildercord.pairs;

import dev.wildercord.cast.PairCast;

/** Runs a written pair's effect, by its two rune paths (alphabetically): false for one not yet written. */
public final class PairIndex {
	private PairIndex() {}

	public static boolean cast(String a, String b, PairCast c) {
		return switch (a) {
			case "absolute_zero" -> dev.wildercord.pairs.gen.C_absolute_zero.cast(b, c);
			case "accelerate" -> dev.wildercord.pairs.gen.C_accelerate.cast(b, c);
			case "aftershock" -> dev.wildercord.pairs.gen.C_aftershock.cast(b, c);
			case "anchor" -> dev.wildercord.pairs.gen.C_anchor.cast(b, c);
			case "banish" -> dev.wildercord.pairs.gen.C_banish.cast(b, c);
			case "barrier" -> dev.wildercord.pairs.gen.C_barrier.cast(b, c);
			case "bleed" -> dev.wildercord.pairs.gen.C_bleed.cast(b, c);
			case "blind" -> dev.wildercord.pairs.gen.C_blind.cast(b, c);
			case "blink" -> dev.wildercord.pairs.gen.C_blink.cast(b, c);
			case "borrowed_time" -> dev.wildercord.pairs.gen.C_borrowed_time.cast(b, c);
			case "bramble" -> dev.wildercord.pairs.gen.C_bramble.cast(b, c);
			case "bubble" -> dev.wildercord.pairs.gen.C_bubble.cast(b, c);
			case "chill" -> dev.wildercord.pairs.gen.C_chill.cast(b, c);
			case "cinderbrand" -> dev.wildercord.pairs.gen.C_cinderbrand.cast(b, c);
			case "cleanse" -> dev.wildercord.pairs.gen.C_cleanse.cast(b, c);
			case "coldsnap" -> dev.wildercord.pairs.gen.C_coldsnap.cast(b, c);
			case "countdown" -> dev.wildercord.pairs.gen.C_countdown.cast(b, c);
			case "cyclone" -> dev.wildercord.pairs.gen.C_cyclone.cast(b, c);
			case "dash" -> dev.wildercord.pairs.gen.C_dash.cast(b, c);
			case "deflect" -> dev.wildercord.pairs.gen.C_deflect.cast(b, c);
			case "ember" -> dev.wildercord.pairs.gen.C_ember.cast(b, c);
			case "empower" -> dev.wildercord.pairs.gen.C_empower.cast(b, c);
			case "evade" -> dev.wildercord.pairs.gen.C_evade.cast(b, c);
			case "fangs" -> dev.wildercord.pairs.gen.C_fangs.cast(b, c);
			case "fire" -> dev.wildercord.pairs.gen.C_fire.cast(b, c);
			case "flash_freeze" -> dev.wildercord.pairs.gen.C_flash_freeze.cast(b, c);
			case "flashfire" -> dev.wildercord.pairs.gen.C_flashfire.cast(b, c);
			case "frost" -> dev.wildercord.pairs.gen.C_frost.cast(b, c);
			case "gale_mantle" -> dev.wildercord.pairs.gen.C_gale_mantle.cast(b, c);
			case "gash" -> dev.wildercord.pairs.gen.C_gash.cast(b, c);
			case "grapple" -> dev.wildercord.pairs.gen.C_grapple.cast(b, c);
			case "grow" -> dev.wildercord.pairs.gen.C_grow.cast(b, c);
			case "haste" -> dev.wildercord.pairs.gen.C_haste.cast(b, c);
			case "haven" -> dev.wildercord.pairs.gen.C_haven.cast(b, c);
			case "heal" -> dev.wildercord.pairs.gen.C_heal.cast(b, c);
			case "hex" -> dev.wildercord.pairs.gen.C_hex.cast(b, c);
			case "hobble" -> dev.wildercord.pairs.gen.C_hobble.cast(b, c);
			case "icicle" -> dev.wildercord.pairs.gen.C_icicle.cast(b, c);
			case "launch" -> dev.wildercord.pairs.gen.C_launch.cast(b, c);
			case "leech" -> dev.wildercord.pairs.gen.C_leech.cast(b, c);
			case "levitate" -> dev.wildercord.pairs.gen.C_levitate.cast(b, c);
			case "lightning" -> dev.wildercord.pairs.gen.C_lightning.cast(b, c);
			case "lure" -> dev.wildercord.pairs.gen.C_lure.cast(b, c);
			case "managift" -> dev.wildercord.pairs.gen.C_managift.cast(b, c);
			case "meteor" -> dev.wildercord.pairs.gen.C_meteor.cast(b, c);
			case "pacify" -> dev.wildercord.pairs.gen.C_pacify.cast(b, c);
			case "pull" -> dev.wildercord.pairs.gen.C_pull.cast(b, c);
			case "push" -> dev.wildercord.pairs.gen.C_push.cast(b, c);
			case "rally" -> dev.wildercord.pairs.gen.C_rally.cast(b, c);
			case "regrowth" -> dev.wildercord.pairs.gen.C_regrowth.cast(b, c);
			case "rend" -> dev.wildercord.pairs.gen.C_rend.cast(b, c);
			case "salve" -> dev.wildercord.pairs.gen.C_salve.cast(b, c);
			case "sentry" -> dev.wildercord.pairs.gen.C_sentry.cast(b, c);
			case "shieldwall" -> dev.wildercord.pairs.gen.C_shieldwall.cast(b, c);
			case "shock" -> dev.wildercord.pairs.gen.C_shock.cast(b, c);
			case "slowburn" -> dev.wildercord.pairs.gen.C_slowburn.cast(b, c);
			case "stillbind" -> dev.wildercord.pairs.gen.C_stillbind.cast(b, c);
			case "stormheart" -> dev.wildercord.pairs.gen.C_stormheart.cast(b, c);
			case "umbra" -> dev.wildercord.pairs.gen.C_umbra.cast(b, c);
			case "undertow" -> dev.wildercord.pairs.gen.C_undertow.cast(b, c);
			default -> false;
		};
	}
}
