// Generated by tools/pairs/index.py from the @Pair methods: do not edit.
package dev.wildercord.pairs;

import dev.wildercord.cast.PairCast;

/** Runs a written pair's effect, by its two rune paths (alphabetically): false for one not yet written. */
public final class PairIndex {
	private PairIndex() {}

	public static boolean cast(String a, String b, PairCast c) {
		return switch (a) {
			case "chill" -> dev.wildercord.pairs.gen.C_chill.cast(b, c);
			default -> false;
		};
	}
}
