// Generated by tools/pairs/index.py from the @Pair methods: do not edit.
package dev.wildercord.pairs;

import dev.wildercord.spell.PairSpec;

/** Every written pair's spec, by its two rune paths (alphabetically): null for one not yet written. */
public final class PairSpecs {
	private PairSpecs() {}

	/** How many pairs are written. */
	public static final int COUNT = 1;

	public static PairSpec spec(String a, String b) {
		return switch (a) {
			case "chill" -> dev.wildercord.pairs.gen.S_chill.spec(b);
			default -> null;
		};
	}
}
