package dev.wildercord.wildlife;
import net.fabricmc.fabric.api.client.gametest.v1.context.*;
import net.minecraft.core.*;
import net.minecraft.server.MinecraftServer;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.world.*;
import net.minecraft.world.entity.*;
import net.minecraft.world.entity.item.ItemEntity;
import net.minecraft.world.inventory.ContainerInput;
import net.minecraft.world.item.*;
import net.minecraft.world.phys.*;
import java.util.*;
import java.util.function.Predicate;
/** Native fixture helpers. Only ordinary vanilla supplies and initial habitats are supplied by tests. */
final class BelowkeeperTestSupport {
 static ServerPlayer p(MinecraftServer s){return s.getPlayerList().getPlayers().getFirst();}
 static void check(boolean value,String why){if(!value)throw new AssertionError(why);}
 static void await(ClientGameTestContext c,TestSingleplayerContext w,Predicate<MinecraftServer> yes,String why){for(int i=0;i<180;i++){c.waitTicks(3);if(w.getServer().computeOnServer(yes::test))return;}throw new AssertionError(why);}
 static void hand(ServerPlayer p,ItemStack stack){var old=p.getMainHandItem();if(!old.isEmpty()){int at=-1;for(int i=9;i<36;i++)if(p.getInventory().getItem(i).isEmpty()){at=i;break;}check(at>=0,"Earned hand contents can be retained");p.getInventory().setItem(at,old);}p.setItemInHand(InteractionHand.MAIN_HAND,stack);}
 static ItemStack take(ServerPlayer p,Item item,int n){for(int i=0;i<36;i++){var stack=p.getInventory().getItem(i);if(stack.is(item) && stack.getCount()>=n)return stack.split(n);}throw new AssertionError("Actual earned ingredient absent: "+item);}
 static void move(ServerPlayer p,double x,double y,double z){p.teleportTo(p.level(),x,y,z,Set.<Relative>of(),90,20,false);}
 static void click(ClientGameTestContext c,TestSingleplayerContext w,BlockPos at,ItemStack held){w.getServer().runOnServer(s -> {var player=p(s);hand(player,held);boolean clear=false;for(double[] side:new double[][]{{0,-1.6},{0,1.6},{-1.6,0},{1.6,0}}){move(player,at.getX()+.5+side[0],at.getY(),at.getZ()+.5+side[1]);if(player.level().noCollision(player,player.getBoundingBox())){var hit=player.level().clip(new net.minecraft.world.level.ClipContext(player.getEyePosition(),Vec3.atCenterOf(at),net.minecraft.world.level.ClipContext.Block.COLLIDER,net.minecraft.world.level.ClipContext.Fluid.NONE,player));if(hit.getType()==HitResult.Type.MISS || hit.getBlockPos().equals(at)){clear=true;break;}}}check(clear,"Actual ledger/plant has a collision-free visible approach");});c.waitTicks(5);c.runOnClient(mc -> mc.gameMode.useItemOn(mc.player,InteractionHand.MAIN_HAND,new BlockHitResult(Vec3.atCenterOf(at),Direction.UP,at,false)));c.waitTicks(5);}
 static void collect(ClientGameTestContext c,TestSingleplayerContext w,Item item,int before,UUID uuid){boolean forward=c.computeOnClient(mc -> mc.options.keyUp.isDown());try {for(int i=0;i<100;i++){Vec3 target=w.getServer().computeOnServer(s -> {if(p(s).getInventory().countItem(item)>before)return null;var e=s.overworld().getEntity(uuid);check(e instanceof ItemEntity,"Exact earned drop remains until the required inventory pickup");return e.position();});if(target==null)return;c.runOnClient(mc -> {var d=target.subtract(mc.player.position());mc.player.setYRot((float)Math.toDegrees(Math.atan2(-d.x,d.z)));mc.options.keyUp.setDown(true);});c.waitTicks(2);}check(w.getServer().computeOnServer(s -> p(s).getInventory().countItem(item)>before),"Actual native movement acquires the earned item");}finally{c.runOnClient(mc -> mc.options.keyUp.setDown(forward));}}
 static void gather(ClientGameTestContext c,TestSingleplayerContext w,SporebackSnail snail){boolean crouch=c.computeOnClient(mc -> mc.options.keyShift.isDown());try {int count=w.getServer().computeOnServer(s -> p(s).getInventory().countItem(SporebackContent.DEW));w.getServer().runOnServer(s -> {hand(p(s),ItemStack.EMPTY);move(p(s),snail.getX()+.9,snail.getY(),snail.getZ());});c.runOnClient(mc -> mc.options.keyShift.setDown(true));c.waitTicks(5);int id=snail.getId();for(int wait=0;wait<100 && !c.computeOnClient(mc -> mc.level.getEntity(id)!=null);wait++)c.waitTicks(2);if(!c.computeOnClient(mc -> mc.level.getEntity(id)!=null)){
 w.getServer().runOnServer(srv -> {var l=srv.overworld();var actual=l.getEntity(snail.getUUID());var player=p(srv);dev.wildercord.Wildercord.LOGGER.info("DRAINHOUSE_GATHER_SERVER snailUuid={} snailId={} snailPos={} alive={} removed={} removalReason={} dew={} pose={} onGround={} water={} chunk={} chunkLoaded={} serverByUUID={} serverByID={} player={} playerChunk={} distance={} now={}",snail.getUUID(),id,snail.position(),snail.isAlive(),snail.isRemoved(),snail.getRemovalReason(),snail.dew(),snail.pose(),snail.onGround(),snail.isInWater(),snail.chunkPosition(),l.hasChunkAt(snail.blockPosition()),actual==snail,l.getEntity(id)==snail,player.position(),player.chunkPosition(),player.distanceToSqr(snail),l.getGameTime());});
 c.runOnClient(mc -> {var actual=mc.level.getEntity(id);var at=snail.blockPosition();dev.wildercord.Wildercord.LOGGER.info("DRAINHOUSE_GATHER_CLIENT expectedUuid={} expectedId={} clientByID={} clientUUID={} player={} playerChunk={} snailChunk={} chunkLoaded={}",snail.getUUID(),id,actual,actual==null?null:actual.getUUID(),mc.player.position(),mc.player.chunkPosition(),snail.chunkPosition(),mc.level.hasChunkAt(at));});
 throw new AssertionError("Actual relocated snail has arrived through native entity tracking before interaction; see exact server/client diagnostics");
}c.runOnClient(mc -> {var e=mc.level.getEntity(id);mc.gameMode.interact(mc.player,e,new EntityHitResult(e,e.getBoundingBox().getCenter()),InteractionHand.MAIN_HAND);});c.waitTicks(3);w.getServer().runOnServer(s -> check(!snail.dew(),"Native crouch gathering spends only the actual visitor reserve"));UUID dropped=w.getServer().computeOnServer(s -> {if(p(s).getInventory().countItem(SporebackContent.DEW)>count)return null;return s.overworld().getEntitiesOfClass(ItemEntity.class,snail.getBoundingBox().inflate(4),e -> e.getItem().is(SporebackContent.DEW)).getFirst().getUUID();});if(dropped!=null)collect(c,w,SporebackContent.DEW,count,dropped);}finally{c.runOnClient(mc -> mc.options.keyShift.setDown(crouch));}}
 static void harvest(ClientGameTestContext c,TestSingleplayerContext w,BlockPos plant){int before=w.getServer().computeOnServer(s -> p(s).getInventory().countItem(FungalGarden.GILLS));click(c,w,plant,ItemStack.EMPTY);UUID dropped=w.getServer().computeOnServer(s -> {check(s.overworld().getBlockState(plant).getValue(GlowcapBlock.AGE)==0,"Actual mature harvest resets the real plant");if(p(s).getInventory().countItem(FungalGarden.GILLS)>before)return null;return s.overworld().getEntitiesOfClass(ItemEntity.class,new AABB(plant).inflate(4),e -> e.getItem().is(FungalGarden.GILLS)).getFirst().getUUID();});if(dropped!=null)collect(c,w,FungalGarden.GILLS,before,dropped);}
 static void readBook(ClientGameTestContext c,TestSingleplayerContext w,Item book,String name){
  w.getServer().runOnServer(s -> hand(p(s),take(p(s),book,1)));c.waitTicks(5);
  c.runOnClient(mc -> mc.gameMode.useItem(mc.player,InteractionHand.MAIN_HAND));c.waitTicks(5);
  check(c.computeOnClient(mc -> mc.gui.screen() instanceof net.minecraft.client.gui.screens.inventory.BookViewScreen),"Actual earned original book opens natively");
  c.runOnClient(mc -> {var access=net.minecraft.client.gui.screens.inventory.BookViewScreen.BookAccess.fromItem(mc.player.getMainHandItem());check(access.getPageCount()==3,"Actual earned book retains all three original pages");for(int page=0;page<3;page++){var text=access.getPage(page);check(text.getString().length()<=210,"Original page stays within authored compact text limit");check(mc.font.split(text,114).size()<=14,"Actual native font wraps the complete original page inside vanilla 128-pixel page height");}});
  for(int page=0;page<3;page++){final int selected=page;c.runOnClient(mc -> {var open=(net.minecraft.client.gui.screens.inventory.BookViewScreen)mc.gui.screen();boolean moved=open.setPage(selected);check(selected==0 || moved,"Actual open earned book advances through its original pages");});c.waitTicks(4);c.takeScreenshot(net.fabricmc.fabric.api.client.gametest.v1.screenshot.TestScreenshotOptions.of(name+"_page_"+(page+1)).disableCounterPrefix());}
  c.runOnClient(mc -> mc.gui.setScreen(null));
 }
 static void craft(ClientGameTestContext c,TestSingleplayerContext w,List<ItemStack> inputs,Item result){w.getServer().runOnServer(s -> {for(int i=0;i<4;i++)p(s).inventoryMenu.getSlot(i+1).set(inputs.get(i));p(s).inventoryMenu.broadcastChanges();check(p(s).inventoryMenu.getSlot(0).getItem().is(result),"Actual native crafting recipe has the expected result");});c.waitTicks(5);c.runOnClient(mc -> mc.gameMode.handleContainerInput(mc.player.inventoryMenu.containerId,0,0,ContainerInput.QUICK_MOVE,mc.player));c.waitTicks(5);w.getServer().runOnServer(s -> check(p(s).getInventory().countItem(result)==1 && p(s).inventoryMenu.getSlot(1).getItem().isEmpty(),"Native result pickup consumes the actual ingredients once"));}
}
