package dev.wildercord.wildlife;

import dev.wildercord.Wildercord;
import dev.wildercord.client.wildlife.CinderBailiffModel;
import dev.wildercord.client.wildlife.CinderBailiffRenderer;
import net.fabricmc.fabric.api.client.gametest.v1.FabricClientGameTest;
import net.fabricmc.fabric.api.client.gametest.v1.context.*;
import net.fabricmc.fabric.api.client.gametest.v1.screenshot.TestScreenshotOptions;
import net.minecraft.client.CameraType;
import net.minecraft.client.KeyMapping;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.core.BlockPos;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.world.InteractionHand;
import net.minecraft.world.effect.*;
import net.minecraft.world.entity.*;
import net.minecraft.world.entity.ai.attributes.Attributes;
import net.minecraft.world.entity.monster.zombie.Zombie;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.level.GameType;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.phys.Vec3;
import java.util.*;

/** Supplied habitat/items/palette; actual registered rig and real AI phases, no pose/deadline injection. */
public final class EmberPresentationTest implements FabricClientGameTest {
 private CinderBailiff actor;private Zombie victim;
 private record Rig(float warning,float fan,float rest,int vent,float bodyY,float headX,float tailX,float[] vents){}
 @Override public void runTest(ClientGameTestContext c){
  var camera=c.computeOnClient(mc->mc.options.getCameraType());var screen=c.computeOnClient(mc->mc.gui.screen());boolean hidden=c.computeOnClient(mc->mc.gui.hud.isHidden());int scale=c.computeOnClient(mc->mc.options.guiScale().get());int[] size=c.computeOnClient(mc->new int[]{mc.getWindow().getWidth(),mc.getWindow().getHeight()});
  boolean[] keys=c.computeOnClient(mc->new boolean[]{mc.options.keyUp.isDown(),mc.options.keyDown.isDown(),mc.options.keyLeft.isDown(),mc.options.keyRight.isDown(),mc.options.keyJump.isDown(),mc.options.keyShift.isDown(),mc.options.keyUse.isDown(),mc.options.keyAttack.isDown()});
  try(var w=c.worldBuilder().create()){
   c.waitTicks(25);w.getServer().runCommand("difficulty normal");w.getServer().runCommand("gamerule spawn_mobs false");w.getServer().runCommand("gamerule random_tick_speed 0");w.getServer().runCommand("time set 18000");
   c.runOnClient(mc->{for(var key:keys(mc))key.setDown(false);mc.options.setCameraType(CameraType.FIRST_PERSON);mc.getWindow().setWindowed(1280,720);mc.options.guiScale().set(2);mc.resizeGui();mc.gui.setScreen(null);if(!mc.gui.hud.isHidden())mc.gui.hud.toggle();});
   w.getServer().runOnServer(s->{var l=s.overworld();for(int x=-8;x<=16;x++)for(int z=-7;z<=7;z++){l.setBlock(new BlockPos(x,100,z),Blocks.GRASS_BLOCK.defaultBlockState(),2);for(int y=101;y<=105;y++)l.setBlock(new BlockPos(x,y,z),Blocks.AIR.defaultBlockState(),2);}var fern=new BlockPos(0,101,0);l.setBlock(fern,EmberContent.FERN.defaultBlockState().setValue(CinderFernBlock.AGE,2),2);
    actor=EmberContent.BAILIFF.create(l,EntitySpawnReason.COMMAND);check(actor!=null,"Registered actor factory");actor.setPersistenceRequired();actor.snapTo(-.5,101,.5,0,0);l.addFreshEntity(actor);var p=s.getPlayerList().getPlayers().getFirst();p.setGameMode(GameType.CREATIVE);p.setNoGravity(true);p.addEffect(new MobEffectInstance(MobEffects.NIGHT_VISION,2400,0,false,false,false));creatureCamera(p,actor);
   });int id=actor.getId();boolean browsing=false;for(int n=0;n<600;n++){c.waitTicks(1);if(n%20==0)w.getServer().runOnServer(srv->{Wildercord.LOGGER.info("EMBER_BROWSE actor={} actorTick={} position={} pose={} alive={} removed={} noAI={} target={} navigation={} fern={} clock={} mealReady={}",actor.getId(),actor.tickCount,actor.position(),actor.pose(),actor.isAlive(),actor.isRemoved(),actor.isNoAi(),actor.getTarget(),actor.getNavigation().getPath(),srv.overworld().getBlockState(new BlockPos(0,101,0)),srv.overworld().getGameTime(),actor.mealReady());habitatDiagnostic(srv);});if(c.computeOnClient(mc->mc.level!=null && mc.level.getEntity(id) instanceof CinderBailiff e && e.pose()==CinderBailiff.BROWSING)){browsing=true;break;}}check(browsing,"Actual reached AI starts a real uninterrupted browse");Rig browse=inspect(c,id,true);check(browse.rest()<.2F,"Browse frame is actual open actor, not injected rest");shot(c,"ember_supplied_habitat_actual_browse");
   await(c,id,e->e.pose()==CinderBailiff.RESTING && e.rest>=.65F,"Real completed meal settles into actual client rest blend");Rig rested=inspect(c,id,false);check(rested.rest()>.6F && rested.bodyY()>17.8F,"Registered rig lowers its original body during real rest");w.getServer().runOnServer(s->{check(actor.mealReady()>s.overworld().getGameTime() && actor.restUntil()>s.overworld().getGameTime() && actor.home().equals(new BlockPos(0,101,0)),"Actual meal owns saved finite home/rest clocks");check(s.overworld().getBlockState(actor.home()).getValue(CinderFernBlock.AGE)==1,"Real browse consumes mature growth");});shot(c,"ember_supplied_habitat_actual_rest");
   // Actual ordinary damage interrupts rest and primes retaliation. Recovery/attack rest expire normally.
   w.getServer().runOnServer(s->{var l=s.overworld();victim=EntityTypes.ZOMBIE.create(l,EntitySpawnReason.COMMAND);check(victim!=null,"Actual physical target factory");victim.setNoAi(true);victim.setPersistenceRequired();victim.getAttribute(Attributes.ARMOR).setBaseValue(0);victim.getAttribute(Attributes.ARMOR_TOUGHNESS).setBaseValue(0);victim.snapTo(actor.getX(),101,actor.getZ()+2.8,0,0);l.addFreshEntity(victim);check(actor.hurtServer(l,victim.damageSources().mobAttack(victim),1),"Genuine ordinary damage starts actor retaliation");creatureCamera(s.getPlayerList().getPlayers().getFirst(),actor);});
   await(c,id,e->e.pose()==CinderBailiff.WARNING && e.warning>=.7F,"Real AI warning reaches original raised ceramic vents");Rig warning=inspect(c,id,false);check(warning.warning()>.6F && warning.vents()[0]<-.2F && warning.vents()[2]<warning.vents()[0],"Real warning lifts three individually ordered vent hinges");shot(c,"ember_supplied_habitat_actual_warning");
   for(int stage=0;stage<3;stage++){final int vent=stage;await(c,id,e->e.pose()==CinderBailiff.FANNING && e.vent()==vent && e.fan>=.3F,"Actual live fan exposes ordered vent "+stage);Rig fan=inspect(c,id,false);check(fan.vent()==stage && fan.fan()>.2F,"Renderer receives actual ordered native vent state");for(int other=0;other<3;other++)if(other!=stage)check(fan.vents()[stage]>fan.vents()[other]+.06F,"Selected vent has its own live hinge release");shot(c,"ember_supplied_habitat_actual_fan_vent_"+stage);}
   await(c,id,e->e.pose()==CinderBailiff.RECOVERING && e.fan<.3F && e.warning<.2F,"Finite real fan returns through its actual recovery blend");Rig recovery=inspect(c,id,false);check(Math.abs(recovery.headX())<.05F,"Recovered original head returns toward neutral");w.getServer().runOnServer(s->check(Math.abs(victim.getHealth()-16)<.001 && actor.attackReady()>s.overworld().getGameTime() && !victim.isOnFire(),"Actual fixed three-lane fan deals one four-point physical strike without burn"));shot(c,"ember_supplied_habitat_actual_recovery");
   // Supplied six-state palette, separate from the earned ecological interaction above.
   w.getServer().runOnServer(s->{var l=s.overworld();for(int age=0;age<3;age++)for(int row=0;row<2;row++)l.setBlock(new BlockPos(8+age*2,101,row*2),EmberContent.FERN.defaultBlockState().setValue(CinderFernBlock.AGE,age).setValue(CinderFernBlock.COOLED,row==0),2);look(s.getPlayerList().getPlayers().getFirst(),new Vec3(10.5,103.5,7.5),new Vec3(10.5,101.45,1.5));});c.waitTicks(12);w.getConnection().waitForChunksRender();c.runOnClient(mc->{for(int age=0;age<3;age++)for(int row=0;row<2;row++){var at=new BlockPos(8+age*2,101,row*2);var state=mc.level.getBlockState(at);check(state.is(EmberContent.FERN) && state.getValue(CinderFernBlock.AGE)==age && state.getValue(CinderFernBlock.COOLED)==(row==0),"Actual client contains all six distinct supplied growth/cooling states");String name="cinder_fern_"+age+"_"+(row==0?"cool":"hot");check(mc.getResourceManager().getResource(Wildercord.id("models/block/"+name+".json")).isPresent(),"Each actual state has its original model resource");}});shot(c,"ember_supplied_six_state_fern_palette");
   for(int which=0;which<2;which++){final boolean egg=which==1;w.getServer().runOnServer(s->{var p=s.getPlayerList().getPlayers().getFirst();p.setGameMode(GameType.SURVIVAL);p.setNoGravity(false);p.setItemInHand(InteractionHand.MAIN_HAND,new ItemStack(egg?EmberContent.EGG:EmberContent.FERN_ITEM));p.getInventory().setItem((p.getInventory().getSelectedSlot()+1)%9,new ItemStack(egg?EmberContent.FERN_ITEM:EmberContent.EGG));p.teleportTo(s.overworld(),10.5,101,5.5,Set.<Relative>of(),180,15,false);p.inventoryMenu.broadcastChanges();});c.runOnClient(mc->{if(mc.gui.hud.isHidden())mc.gui.hud.toggle();});c.waitTicks(15);check(c.computeOnClient(mc->mc.player.getMainHandItem().is(egg?EmberContent.EGG:EmberContent.FERN_ITEM)),"Actual supplied custom item reaches rendered hand/hotbar");shot(c,egg?"ember_supplied_egg_held_and_icons":"ember_supplied_root_held_and_icons");}
  }finally{actor=null;victim=null;c.runOnClient(mc->{mc.gui.setScreen(screen);mc.options.setCameraType(camera);if(mc.player!=null)mc.setCameraEntity(mc.player);if(mc.gui.hud.isHidden()!=hidden)mc.gui.hud.toggle();mc.options.guiScale().set(scale);mc.getWindow().setWindowed(size[0],size[1]);mc.resizeGui();var mappings=keys(mc);for(int i=0;i<keys.length;i++)mappings[i].setDown(keys[i]);});}
 }

 /** Same thirty existing poll snapshots; reads only, no goal invocation/path search/RNG or waits. */
 private void habitatDiagnostic(net.minecraft.server.MinecraftServer s){
  try{
   var f=net.minecraft.world.entity.Mob.class.getDeclaredField("goalSelector");f.setAccessible(true);
   var selector=(net.minecraft.world.entity.ai.goal.GoalSelector)f.get(actor);
   var status=new ArrayList<String>(6);EmberHabitatGoal habitat=null;boolean running=false;
   for(var wrapped:selector.getAvailableGoals()){
    if(wrapped.isRunning())status.add(wrapped.getGoal().getClass().getName()+":"+wrapped.getPriority());
    if(wrapped.getGoal() instanceof EmberHabitatGoal h){habitat=h;running=wrapped.isRunning();}
   }
   check(habitat!=null,"Actual registered habitat goal exists");
   var sweep=field(habitat,"sweep",HabitatSweep.class);var fern=field(habitat,"fern",BlockPos.class);var path=actor.getNavigation().getPath();
   var root=new BlockPos(0,101,0);var clip=s.overworld().clip(new net.minecraft.world.level.ClipContext(actor.getEyePosition(),Vec3.atCenterOf(root),net.minecraft.world.level.ClipContext.Block.COLLIDER,net.minecraft.world.level.ClipContext.Fluid.NONE,actor));
   Wildercord.LOGGER.info("EMBER_HABITAT running={} activeGoals={} mayBrowse={} searchAt={} scanAt={} left={} chew={} retries={} sweepCursor={} sweepAnchor={} retainedFern={} pathEnd={} pathCanReach={} rootDistanceSquared={} eye={} colliderClip={} foot={} rootFoot={} rootSurvives={} fluid={} effectiveAI={} entityTicking={} spectatorGenerates={}",running,status,actor.mayBrowse(),field(habitat,"searchAt",Integer.class),field(habitat,"scanAt",Integer.class),field(habitat,"left",Integer.class),field(habitat,"chew",Integer.class),field(habitat,"retries",Integer.class),sweep==null?-1:field(sweep,"cursor",Integer.class),sweep==null?"none":new BlockPos(sweep.x(),sweep.y(),sweep.z()),fern,path==null?"none":path.getEndNode(),path!=null&&path.canReach(),actor.distanceToSqr(root.getX()+.5,root.getY(),root.getZ()+.5),actor.getEyePosition(),clip.getType(),s.overworld().getBlockState(actor.blockPosition().below()),s.overworld().getBlockState(root.below()),s.overworld().getBlockState(root).canSurvive(s.overworld(),root),s.overworld().getFluidState(actor.blockPosition()),actor.isEffectiveAi(),s.overworld().isPositionEntityTicking(actor.blockPosition()),s.overworld().getGameRules().get(net.minecraft.world.level.gamerules.GameRules.SPECTATORS_GENERATE_CHUNKS));
  }catch(ReflectiveOperationException e){throw new AssertionError(e);}
 }
 private static KeyMapping[] keys(net.minecraft.client.Minecraft mc){return new KeyMapping[]{mc.options.keyUp,mc.options.keyDown,mc.options.keyLeft,mc.options.keyRight,mc.options.keyJump,mc.options.keyShift,mc.options.keyUse,mc.options.keyAttack};}
 private static void creatureCamera(ServerPlayer p,CinderBailiff e){look(p,e.position().add(3.6,2.35,3.5),e.getBoundingBox().getCenter().add(0,.05,0));}
 private static void look(ServerPlayer p,Vec3 eye,Vec3 focus){var d=focus.subtract(eye);p.teleportTo(p.level(),eye.x,eye.y-p.getEyeHeight(),eye.z,Set.<Relative>of(),(float)Math.toDegrees(Math.atan2(-d.x,d.z)),(float)-Math.toDegrees(Math.atan2(d.y,d.horizontalDistance())),false);}
 private static Rig inspect(ClientGameTestContext c,int id,boolean material){return c.computeOnClient(mc->{check(mc.level.getEntity(id) instanceof CinderBailiff,"Actual tracked custom creature");var e=(CinderBailiff)mc.level.getEntity(id);var raw=mc.getEntityRenderDispatcher().getRenderer(e);check(raw instanceof CinderBailiffRenderer,"Entity selects original registered renderer");var renderer=(CinderBailiffRenderer)raw;var state=renderer.createRenderState(e,.5F);CinderBailiffModel model=renderer.getModel();model.setupAnim(state);var legs=field(model,"legs",ModelPart[].class);var vents=field(model,"vents",ModelPart[].class);check(legs.length==4 && vents.length==3,"Original rig contains four feet and three vent hinges");var unique=Collections.newSetFromMap(new IdentityHashMap<ModelPart,Boolean>());for(var leg:legs)check(unique.add(leg) && !leg.getChild("toe").isEmpty(),"Each foot has an independent sculpted toe");for(var vent:vents)check(unique.add(vent) && !vent.getChild("slats").isEmpty(),"Every vent has independent material slats");var body=field(model,"body",ModelPart.class);var head=field(model,"head",ModelPart.class);var tail=field(model,"tail",ModelPart.class);check(!body.getChild("breastplate").isEmpty(),"Original ceramic breastplate exists");for(int side:new int[]{-1,1})check(!head.getChild("ear_"+side).isEmpty() && !head.getChild("eye_"+side).isEmpty(),"Original ear/eye silhouette exists");for(int n=0;n<4;n++)check(!tail.getChild("scale_"+n).isEmpty(),"All four original tail scales exist");check(renderer.getTextureLocation(state).equals(Wildercord.id("textures/entity/cinder_bailiff.png")),"Actual authored material binding");
   if(material)try(var stream=mc.getResourceManager().getResource(renderer.getTextureLocation(state)).orElseThrow().open()){var image=javax.imageio.ImageIO.read(stream);check(image!=null && image.getWidth()==128 && image.getHeight()==128,"Actual128-square authored material loads");var colors=new HashSet<Integer>();int opaque=0;for(int y=0;y<128;y++)for(int x=0;x<128;x++){int argb=image.getRGB(x,y);if((argb>>>24)>0){opaque++;colors.add(argb);}}check(opaque>500 && colors.size()>24,"Material has real opaque shaded detail");}catch(java.io.IOException failure){throw new AssertionError(failure);}
   var result=new Rig(state.warning,state.fan,state.rest,state.vent,body.y,head.xRot,tail.xRot,new float[]{vents[0].xRot,vents[1].xRot,vents[2].xRot});Wildercord.LOGGER.info("EMBER_PRESENTATION actor={} clientPose={} warning={} fan={} rest={} selectedVent={} hingeRotations={}",id,e.pose(),result.warning(),result.fan(),result.rest(),result.vent(),Arrays.toString(result.vents()));return result;
  });}
 private static <T>T field(Object o,String name,Class<T> type){try{var f=o.getClass().getDeclaredField(name);f.setAccessible(true);return type.cast(f.get(o));}catch(ReflectiveOperationException failure){throw new AssertionError(failure);}}
 private static void await(ClientGameTestContext c,int id,java.util.function.Predicate<CinderBailiff> yes,String why){for(int n=0;n<600;n++){c.waitTicks(1);if(c.computeOnClient(mc->mc.level!=null && mc.level.getEntity(id) instanceof CinderBailiff e && yes.test(e)))return;}throw new AssertionError(why);}
 private static void shot(ClientGameTestContext c,String name){c.runOnClient(mc->{mc.gui.toastManager().clear();mc.gui.hud.getChat().clearMessages(false);});c.takeScreenshot(TestScreenshotOptions.of(name).disableCounterPrefix());}
 private static void check(boolean yes,String why){if(!yes)throw new AssertionError(why);}
}
