package dev.wildercord.wildlife;
import static dev.wildercord.wildlife.TidewardNative.*;
import dev.wildercord.client.fx.*;
import net.fabricmc.fabric.api.client.gametest.v1.FabricClientGameTest;
import net.fabricmc.fabric.api.client.gametest.v1.context.*;
import net.minecraft.client.*;
import net.minecraft.client.particle.*;
import net.minecraft.core.BlockPos;
import net.minecraft.world.*;
import net.minecraft.world.entity.*;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.level.GameType;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.phys.*;
import java.util.*;
import java.util.concurrent.CompletableFuture;
/** Supplied fan and dry footing. All physical beats follow actual held use and real vanilla arrow collision. */
public final class RainshieldPresentationTest implements FabricClientGameTest {
 public void runTest(ClientGameTestContext c){try(var settings=new TidewardNative(c)){c.runOnClient(mc->{mc.getWindow().setWindowed(1920,1080);mc.resizeGui();});for(var quality:List.of(MagicQuality.Level.FULL,MagicQuality.Level.MINIMAL)){
  String prefix="rainshield_"+quality.name().toLowerCase(Locale.ROOT);
  try(var w=c.worldBuilder().create()){scene(c,w,quality);shot(c,prefix+"_actual_supplied_held_fan");c.runOnClient(mc->{mc.options.setCameraType(CameraType.FIRST_PERSON);if(mc.gui.hud.isHidden())mc.gui.hud.toggle();});c.waitTicks(2);shot(c,prefix+"_actual_supplied_held_firstperson");c.runOnClient(mc->{mc.options.setCameraType(CameraType.THIRD_PERSON_FRONT);clean(mc);});c.waitTicks(2);start(c);c.waitFor(mc->!pieces(mc,0).isEmpty(),20);paired(c,prefix+"_actual_pivot_prep",0,quality==MagicQuality.Level.MINIMAL?3:7);c.waitFor(mc->!pieces(mc,1).isEmpty(),30);paired(c,prefix+"_actual_unfolded_cloth",1,quality==MagicQuality.Level.MINIMAL?4:10);c.runOnClient(mc->mc.options.keyUse.setDown(false));}
  try(var w=c.worldBuilder().create()){scene(c,w,quality);start(c);c.waitTicks(16);c.runOnClient(mc->{mc.options.setCameraType(CameraType.FIRST_PERSON);if(mc.gui.hud.isHidden())mc.gui.hud.toggle();});c.waitTicks(2);shot(c,prefix+"_actual_prepared_firstperson");c.runOnClient(mc->{mc.options.setCameraType(CameraType.THIRD_PERSON_FRONT);clean(mc);});c.waitTicks(2);w.getServer().runOnServer(s->{var p=player(s);check(RooksRainshield.active(p)&&p.getTicksUsingItem()>=12,"Catch scene has actual native planted fan");var a=EntityTypes.ARROW.create(s.overworld(),EntitySpawnReason.COMMAND);check(a!=null,"Real vanilla arrow creation");a.snapTo(-3.5,102.1,.5,0,0);a.setDeltaMovement(new Vec3(.65,0,0));a.setBaseDamage(2);s.overworld().addFreshEntity(a);});c.waitFor(mc->!pieces(mc,2).isEmpty(),30);w.getServer().runOnServer(s->{var p=player(s);check(p.getHealth()==20&&p.getMainHandItem().getDamageValue()==4&&!RooksRainshield.active(p)&&p.getAttachedOrElse(RooksRainshield.READY,0L)>s.overworld().getGameTime(),"Review catch beat belongs to actual spent physical impact");});paired(c,prefix+"_actual_arrow_catch",2,1);c.runOnClient(mc->mc.options.keyUse.setDown(false));}
 }}}
 private static void scene(ClientGameTestContext c,TestSingleplayerContext w,MagicQuality.Level quality){c.waitTicks(25);w.getServer().runCommand("gamerule spawn_mobs false");w.getServer().runCommand("difficulty normal");w.getServer().runCommand("time set 6000");w.getServer().runOnServer(s->{var l=s.overworld();for(int x=-7;x<=7;x++)for(int z=-4;z<=4;z++){l.setBlock(new BlockPos(x,100,z),Blocks.STONE.defaultBlockState(),2);for(int y=101;y<=105;y++)l.setBlock(new BlockPos(x,y,z),Blocks.AIR.defaultBlockState(),2);}var p=player(s);p.setGameMode(GameType.SURVIVAL);p.teleportTo(l,.5,101,.5,Set.<Relative>of(),90,0,false);p.getInventory().clearContent();p.setItemInHand(InteractionHand.MAIN_HAND,new ItemStack(RooksRainshield.ITEM));p.setHealth(20);});c.waitTicks(6);c.runOnClient(mc->{MagicQuality.own=quality;MagicQuality.others=quality;mc.options.setCameraType(CameraType.THIRD_PERSON_FRONT);clean(mc);});c.waitTicks(2);}
 private static void start(ClientGameTestContext c){c.runOnClient(mc->{mc.options.keyUse.setDown(true);mc.gameMode.useItem(mc.player,InteractionHand.MAIN_HAND);});}
 private static void clean(Minecraft mc){mc.gui.setScreen(null);mc.gui.toastManager().clear();mc.gui.hud.getChat().clearMessages(false);if(!mc.gui.hud.isHidden())mc.gui.hud.toggle();}
 private static List<Particle> pieces(Minecraft mc,int beat){return particles(mc.particleEngine).stream().filter(p->p.isAlive()&&p.getClass().getName().equals("dev.wildercord.client.fx.RainshieldClient$Piece")&&((RainshieldFx.Event)field(p,p.getClass(),"e")).beat()==beat).toList();}
 private static void paired(ClientGameTestContext c,String name,int beat,int minimum){var done=c.computeOnClient(mc->{clean(mc);var live=pieces(mc,beat);check(live.size()>=minimum,"Retained actual fan materials match quality contract: "+name+" count="+live.size());for(var p:live){var at=new Vec3(number(p,"x"),number(p,"y"),number(p,"z"));check(at.distanceToSqr(mc.player.position())<4,"Actual physical fan stays within recipient foreground");check(beat==2?at.y>=102.03&&at.y<=102.16:at.y>=102.17&&at.y<=102.26,"Actual physical fan material stays around the authored chest pivot, below the standing face: beat="+beat+" y="+at.y);}var a=pixels(mc,name);mc.particleEngine.clearParticles();var b=pixels(mc,name+"_background");return a.thenCombine(b,(drawn,background)->{check(drawn.length==background.length,"Matched actual render dimensions");int changed=0;for(int i=0;i<drawn.length;i++){int x=drawn[i],y=background[i];int d=Math.abs((x>>16&255)-(y>>16&255))+Math.abs((x>>8&255)-(y>>8&255))+Math.abs((x&255)-(y&255));if(d>20)changed++;}check(changed>10,"Actual physical material changes native pixels: "+name+" changed="+changed);return (Void)null;});});c.waitFor(mc->done.isDone());done.join();}
 private static double number(Particle p,String name){return ((Number)field(p,Particle.class,name)).doubleValue();}
 private static Object field(Object o,Class<?> owner,String name){try{var f=owner.getDeclaredField(name);f.setAccessible(true);return f.get(o);}catch(ReflectiveOperationException e){throw new AssertionError(e);}}
 private static List<Particle> particles(ParticleEngine e){var out=new ArrayList<Particle>();for(var group:((Map<?,?>)field(e,ParticleEngine.class,"particles")).values())for(var p:(Queue<?>)field(group,ParticleGroup.class,"particles"))out.add((Particle)p);return out;}
 private static CompletableFuture<int[]> pixels(Minecraft mc,String name){var result=new CompletableFuture<int[]>();mc.gameRenderer.update(DeltaTracker.ONE);mc.gameRenderer.extract(DeltaTracker.ONE,true);mc.gameRenderer.render();com.mojang.blaze3d.systems.RenderSystem.getDevice().createCommandEncoder().submit();net.minecraft.client.Screenshot.takeScreenshot(mc.gameRenderer.mainRenderTarget(),image->{try(image){var path=java.nio.file.Path.of("screenshots",name+".png");java.nio.file.Files.createDirectories(path.getParent());image.writeToFile(path);result.complete(image.getPixels());}catch(Throwable e){result.completeExceptionally(e);}});return result;}
}
