package dev.wildercord.wildlife;
import net.fabricmc.fabric.api.client.gametest.v1.*;
import net.fabricmc.fabric.api.client.gametest.v1.context.*;
import net.fabricmc.fabric.api.client.gametest.v1.world.TestWorldSave;
import net.minecraft.core.BlockPos;
import net.minecraft.server.MinecraftServer;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.world.*;
import net.minecraft.world.entity.*;
import net.minecraft.world.entity.projectile.arrow.Arrow;
import net.minecraft.world.item.*;
import net.minecraft.world.level.GameType;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.phys.Vec3;
import java.util.Set;
/** Supplied relic combat scene: native item use and actual vanilla arrow physics/collision, not earned acquisition. */
public final class RainshieldCollisionTest implements FabricClientGameTest {
 private Arrow front,second;private net.minecraft.world.entity.projectile.arrow.AbstractArrow spectral;private long ready;private TestWorldSave save;
 private static ServerPlayer p(MinecraftServer s){return s.getPlayerList().getPlayers().getFirst();}
 private static void check(boolean x,String why){if(!x)throw new AssertionError(why);}
 private static void setup(MinecraftServer s){var l=s.overworld();for(int x=-7;x<=7;x++)for(int z=-4;z<=4;z++){l.setBlock(new BlockPos(x,100,z),Blocks.STONE.defaultBlockState(),2);for(int y=101;y<=105;y++)l.setBlock(new BlockPos(x,y,z),Blocks.AIR.defaultBlockState(),2);}var p=p(s);p.setGameMode(GameType.SURVIVAL);p.teleportTo(l,.5,101,.5,Set.of(),90,0,false);p.getInventory().clearContent();p.setItemInHand(InteractionHand.MAIN_HAND,new ItemStack(RooksRainshield.ITEM));p.setHealth(20);p.getFoodData().setFoodLevel(20);}
 private static Arrow arrow(MinecraftServer s,boolean rear){var l=s.overworld();var a=EntityTypes.ARROW.create(l,EntitySpawnReason.COMMAND);check(a!=null,"Real vanilla arrow factory");a.snapTo(rear?4.5:-3.5,102.1,.5,0,0);a.setDeltaMovement(new Vec3(rear?-.65:.65,0,0));a.setBaseDamage(2);l.addFreshEntity(a);return a;}
 private static void use(ClientGameTestContext c){c.runOnClient(mc->{mc.gui.setScreen(null);mc.options.keyUse.setDown(true);mc.gameMode.useItem(mc.player,InteractionHand.MAIN_HAND);});}
 public void runTest(ClientGameTestContext c){boolean use=c.computeOnClient(mc->mc.options.keyUse.isDown());try(var settings=new TidewardNative(c)){
  try(var w=c.worldBuilder().create()){c.waitTicks(25);w.getServer().runCommand("gamerule spawn_mobs false");w.getServer().runCommand("difficulty normal");w.getServer().runOnServer(RainshieldCollisionTest::setup);c.waitTicks(6);use(c);c.waitTicks(16);w.getServer().runOnServer(s->{check(RooksRainshield.active(p(s))&&p(s).getTicksUsingItem()>=RooksRainshield.PREP,"Actual native use establishes planted commitment");front=arrow(s,false);});c.waitTicks(12);
   ready=w.getServer().computeOnServer(s->{check(front.isRemoved()&&p(s).getHealth()==20,"Real frontal arrow collision is caught without physical damage");check(p(s).getMainHandItem().getDamageValue()==4&&!RooksRainshield.active(p(s)),"One actual catch spends exact wear and closes fan");check(p(s).hasEffect(net.minecraft.world.effect.MobEffects.MINING_FATIGUE),"Actual catch leaves heavy hands");long deadline=p(s).getAttachedOrElse(RooksRainshield.READY,0L);check(deadline>s.overworld().getGameTime()&&deadline<=s.overworld().getGameTime()+RooksRainshield.REST,"Actual catch reserves finite shared rest");check(p(s).getInventory().countItem(Items.ARROW)==0,"Caught arrow cannot become pickup resource");second=arrow(s,false);return deadline;});c.waitTicks(12);w.getServer().runOnServer(s->{check(p(s).getHealth()<20,"A second actual arrow remains damaging after one catch");check(p(s).getMainHandItem().getDamageValue()==4&&p(s).getAttachedOrElse(RooksRainshield.READY,0L)==ready,"Second impact cannot spend again or renew rest");});c.runOnClient(mc->mc.options.keyUse.setDown(false));save=w.getWorldSave();
  }
  try(var w=save.open()){c.waitTicks(8);w.getServer().runOnServer(s->{check(!RooksRainshield.active(p(s)),"Restart never restores active preparation");check(p(s).getAttachedOrElse(RooksRainshield.READY,0L)==ready,"Exact earned catch deadline persists");p(s).setItemInHand(InteractionHand.MAIN_HAND,new ItemStack(RooksRainshield.ITEM));});c.waitTicks(5);use(c);c.waitTicks(3);w.getServer().runOnServer(s->check(!RooksRainshield.active(p(s))&&p(s).getMainHandItem().getDamageValue()==0&&p(s).getAttachedOrElse(RooksRainshield.READY,0L)==ready,"New copy and reconnect cannot evade or renew earned rest"));c.runOnClient(mc->mc.options.keyUse.setDown(false));}
  try(var w=c.worldBuilder().create()){c.waitTicks(25);w.getServer().runCommand("gamerule spawn_mobs false");w.getServer().runCommand("difficulty normal");w.getServer().runOnServer(RainshieldCollisionTest::setup);c.waitTicks(6);use(c);c.waitTicks(16);w.getServer().runOnServer(s->{check(RooksRainshield.active(p(s)),"Rear refusal begins from real prepared fan");front=arrow(s,true);});c.waitTicks(12);w.getServer().runOnServer(s->check(p(s).getHealth()<20&&p(s).getMainHandItem().getDamageValue()==0&&p(s).getAttachedOrElse(RooksRainshield.READY,0L)==0,"Rear physical arrow is harmful and earns no wear/rest"));}

  try(var w=c.worldBuilder().create()){c.waitTicks(25);w.getServer().runCommand("gamerule spawn_mobs false");w.getServer().runCommand("difficulty normal");w.getServer().runOnServer(RainshieldCollisionTest::setup);c.waitTicks(6);use(c);c.waitTicks(16);w.getServer().runOnServer(s->{check(RooksRainshield.active(p(s)),"Imbued-order refusal begins from actual prepared fan");front=arrow(s,false);front.setAttached(dev.wildercord.player.WildercordAttachments.IMBUED_SHOT,new dev.wildercord.player.WildercordAttachments.ImbuedShot(java.util.List.of("wildercord:heal"),0x8ED1A7));});c.waitTicks(12);w.getServer().runOnServer(s->check(p(s).getHealth()<20&&p(s).getMainHandItem().getDamageValue()==0&&p(s).getAttachedOrElse(RooksRainshield.READY,0L)==0,"Actual arrow collision refuses supplied magical metadata BEFORE Imbuing removes it; no paid-spell claim"));c.runOnClient(mc->mc.options.keyUse.setDown(false));}
  try(var w=c.worldBuilder().create()){c.waitTicks(25);w.getServer().runCommand("gamerule spawn_mobs false");w.getServer().runCommand("difficulty normal");w.getServer().runOnServer(RainshieldCollisionTest::setup);c.waitTicks(6);use(c);c.waitTicks(16);w.getServer().runOnServer(s->{check(RooksRainshield.active(p(s)),"Spectral positive begins from actual prepared fan");spectral=EntityTypes.SPECTRAL_ARROW.create(s.overworld(),EntitySpawnReason.COMMAND);check(spectral!=null,"Actual vanilla spectral factory");spectral.snapTo(-3.5,102.1,.5,0,0);spectral.setDeltaMovement(new Vec3(.65,0,0));spectral.setBaseDamage(2);s.overworld().addFreshEntity(spectral);});c.waitTicks(12);w.getServer().runOnServer(s->check(spectral.isRemoved()&&p(s).getHealth()==20&&!p(s).hasEffect(net.minecraft.world.effect.MobEffects.GLOWING)&&p(s).getMainHandItem().getDamageValue()==4,"Real spectral arrow catch precedes damage/glow and spends one wear"));c.runOnClient(mc->mc.options.keyUse.setDown(false));}
 }finally{c.runOnClient(mc->mc.options.keyUse.setDown(use));}}
}
