package dev.wildercord.gametest;
import dev.wildercord.cast.*;
import dev.wildercord.client.fx.*;
import dev.wildercord.player.*;
import dev.wildercord.spell.*;
import net.fabricmc.fabric.api.client.gametest.v1.FabricClientGameTest;
import net.fabricmc.fabric.api.client.gametest.v1.context.*;
import net.fabricmc.fabric.api.client.networking.v1.ClientPlayNetworking;
import net.minecraft.client.gui.screens.*;
import net.minecraft.client.multiplayer.ServerData;
import net.minecraft.client.multiplayer.resolver.ServerAddress;
import net.minecraft.core.BlockPos;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.world.entity.Relative;
import net.minecraft.world.level.GameType;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.item.ItemStack;
import java.net.InetSocketAddress;
import java.nio.file.*;
import java.util.*;
import java.util.function.BooleanSupplier;
/** Two actual client JVMs/TCP profiles: paid lossy donation, real fresh crouch, expiry and private watch transport. Supplied progression. */
public final class WildercordTwoClientsCampTest implements FabricClientGameTest {
 private final java.util.concurrent.atomic.AtomicInteger transferCount=new java.util.concurrent.atomic.AtomicInteger();private Path directory;private String nonce;private int price;private long donorRest,receiverRest;private ConnectionOwner connections;private java.util.concurrent.atomic.AtomicReference<Manabraid.Transfer> committed=new java.util.concurrent.atomic.AtomicReference<>();
 public void runTest(ClientGameTestContext c){directory=Path.of(System.getProperty("wildercord.mp.directory")).toAbsolutePath();nonce=System.getProperty("wildercord.mp.nonce");check(nonce!=null&&!nonce.isBlank(),"Explicit per-run nonce required");try{if("host".equals(System.getProperty("wildercord.mp.role")))host(c);else if("peer".equals(System.getProperty("wildercord.mp.role")))peer(c);else throw new AssertionError("Explicit host/peer role required");}catch(Throwable e){write(System.getProperty("wildercord.mp.role")+"-failure",Map.of("error",e.toString()));throw e;}}
 private void host(ClientGameTestContext c){
  var properties=new Properties();properties.setProperty("server-ip","127.0.0.1");properties.setProperty("server-port",Integer.toString(localPort()));properties.setProperty("max-players","2");properties.setProperty("white-list","false");properties.setProperty("online-mode","false");properties.setProperty("enforce-secure-profile","false");properties.setProperty("view-distance","5");properties.setProperty("simulation-distance","5");
  try(var server=c.worldBuilder().createServer(properties);var owner=new ConnectionOwner(server.connect())){
   connections=owner;var connection=owner.current();
   connection.waitForChunksDownload();connection.waitForClientboundPackets();UUID host=c.computeOnClient(mc->mc.player.getUUID());long pid=ProcessHandle.current().pid();int port=server.computeOnServer(s->s.getPort());write("host-ready",Map.of("port",""+port,"pid",""+pid,"uuid",host.toString()));
   await(c,()->exists("peer-connected")&&server.computeOnServer(s->s.getPlayerList().getPlayers().size()==2),"Actual peer TCP joins");UUID peer=UUID.fromString(read("peer-connected").getProperty("uuid"));check(Long.parseLong(read("peer-connected").getProperty("pid"))!=pid&&!peer.equals(host),"Distinct client JVM and profile");
   var original=server.computeOnServer(s->dev.wildercord.config.Config.get());var oldQuality=c.computeOnClient(mc->List.of(MagicQuality.own,MagicQuality.others));
   AutoCloseable observation=server.computeOnServer(s->Manabraid.observe(e->{committed.set(e);transferCount.incrementAndGet();}));
   try{
    server.runOnServer(s->{var h=s.getPlayerList().getPlayer(host);var p=s.getPlayerList().getPlayer(peer);check(!tcp(h).equals(tcp(p)),"Distinct real remote loopback TCP sockets");current(copy(original,Map.of("manaRegenMultiplier",0.0,"spellsEditBlocks",false)));
     for(int x=-9;x<=9;x++)for(int z=-9;z<=9;z++){s.overworld().setBlock(new BlockPos(x,100,z),Blocks.STONE.defaultBlockState(),2);for(int y=101;y<=106;y++)s.overworld().setBlock(new BlockPos(x,y,z),Blocks.AIR.defaultBlockState(),2);}for(var actor:List.of(h,p))prepare(actor);h.teleportTo(s.overworld(),.5,101,.5,Set.<Relative>of(),0,0,false);p.teleportTo(s.overworld(),2.5,101,.5,Set.<Relative>of(),90,0,false);
     var rs=List.of(Runes.TOUCH,Runes.get("wildercord:manabraid").orElseThrow(),Runes.ECHO);check(SpellCaster.edit(h,0,rs.stream().map(RuneDef::id).toList())==null,"Actual editor admits learned mana gift with Echo");price=Heart.manaCost(h,SpellCompiler.compile(rs),Heart.secretCost(h,rs)*Mastery.costFactor(h,rs));Spellbooks.setMana(h,80);Spellbooks.setMana(p,0);
    });server.runCommand("gamerule spawn_mobs false");server.runCommand("gamerule fall_damage false");c.runOnClient(mc->{MagicQuality.own=MagicQuality.Level.FULL;MagicQuality.others=MagicQuality.Level.MINIMAL;});
    // Nonallies are refused even before saved rests could hide the policy gate.
    aim(c,peer);cast(c);c.waitTicks(12);server.runOnServer(s->{var h=s.getPlayerList().getPlayer(host);var p=s.getPlayerList().getPlayer(peer);check(!Targets.canHelp(h,p)&&Manabraid.active()==0&&Spellbooks.mana(h)==80-price&&Spellbooks.mana(p)==0,"Actual paid nonally packet cannot transfer or offer");});
    waitReady(c,server,host);server.runCommand("team add wc_camp");server.runCommand("team join wc_camp "+server.computeOnServer(s->s.getPlayerList().getPlayer(host).getGameProfile().name()));server.runCommand("team join wc_camp "+server.computeOnServer(s->s.getPlayerList().getPlayer(peer).getGameProfile().name()));
    server.runOnServer(s->ManabraidFaultCases.direct(s.getPlayerList().getPlayer(host),s.getPlayerList().getPlayer(peer)));
    server.runOnServer(s->Spellbooks.setMana(s.getPlayerList().getPlayer(host),160)); // Separate supplied resource setup for the extended negative/positive sequence.
    write("hold-peer",Map.of());await(c,()->exists("peer-held")&&server.computeOnServer(s->s.getPlayerList().getPlayer(peer).isShiftKeyDown()),"Actual peer holds crouch before offer");
    departures(c,server,host,peer);
    waitReady(c,server,host);aim(c,peer);float beforeCapacity=server.computeOnServer(s->Spellbooks.mana(s.getPlayerList().getPlayer(host)));cast(c);c.waitTicks(8);server.runOnServer(s->{check(Manabraid.active()==1,"Positive real paid offer precedes capacity change");var p=s.getPlayerList().getPlayer(peer);Spellbooks.setMana(p,Mana.max(p));});write("capacity-peer",Map.of());await(c,()->exists("peer-capacity-edge"),"Actual fresh peer consent after target fills");c.waitTicks(3);server.runOnServer(s->{var h=s.getPlayerList().getPlayer(host);var p=s.getPlayerList().getPlayer(peer);check(Manabraid.active()==0&&committed.get()==null&&Spellbooks.mana(h)==beforeCapacity-price&&Spellbooks.mana(p)==Mana.max(p),"No-need acceptance preserves actual filled resource, normal spell price, and zero donation");check(h.getAttachedOrElse(Manabraid.DONOR_READY,0L)==0&&p.getAttachedOrElse(Manabraid.RECEIVE_READY,0L)==0,"No-capacity gift has no successful saved rests");Spellbooks.setMana(p,0);});write("hold-expiry-peer",Map.of());await(c,()->exists("peer-expiry-held")&&server.computeOnServer(s->s.getPlayerList().getPlayer(peer).isShiftKeyDown()),"Real peer holds again before expiry case");waitReady(c,server,host);aim(c,peer);
    cast(c);c.waitTicks(8);server.runOnServer(s->check(Manabraid.active()==1&&committed.get()==null,"Real paid offer has no donation debit/credit; Echo shares same one-offer budget"));c.waitTicks(70);server.runOnServer(s->{check(Manabraid.active()==0&&committed.get()==null&&Spellbooks.mana(s.getPlayerList().getPlayer(peer))==0,"Held crouch has no fresh consent; actual expiry grants no mana");});
    waitReady(c,server,host);cast(c);c.waitTicks(8);float faultBefore=server.computeOnServer(s->{check(Manabraid.active()==1,"Actual paid fault offer remains transient");return ManabraidFaultCases.injectAcceptance(s.getPlayerList().getPlayer(host),s.getPlayerList().getPlayer(peer));});write("fault-accept-peer",Map.of());await(c,()->exists("peer-fault-edge"),"Real release/press consent reaches callback-refused gift");c.waitTicks(5);server.runOnServer(s->{ManabraidFaultCases.verifyAcceptance(s.getPlayerList().getPlayer(host),s.getPlayerList().getPlayer(peer),faultBefore);check(committed.get()==null,"Changed resource callback produces no completed resource/FX observation");});
    waitReady(c,server,host);RuneDef earned=learnManaWeave(c,server,host);float wovenBefore=server.computeOnServer(s->{var h=s.getPlayerList().getPlayer(host);var p=s.getPlayerList().getPlayer(peer);var rs=List.of(Runes.TOUCH,earned,Runes.ECHO);check(Spellbooks.knows(h,earned.id())&&SpellCaster.edit(h,0,rs.stream().map(RuneDef::id).toList())==null,"Actual altar-learned weave is admitted by editor");price=Heart.manaCost(h,SpellCompiler.compile(rs),Heart.secretCost(h,rs)*Mastery.costFactor(h,rs));Spellbooks.setMana(h,80);check(Spellbooks.mana(h)>=price+24,"Existing supplied donor pool can pay the actual woven spell and finite gift");p.setHealth(8);return Spellbooks.mana(h);});aim(c,peer);cast(c);c.waitTicks(8);server.runOnServer(s->check(Manabraid.active()==1&&Spellbooks.mana(s.getPlayerList().getPlayer(host))==wovenBefore-price&&s.getPlayerList().getPlayer(peer).getHealth()>8,"Actual learned woven cast pays its normal price, heals real ally, and offers once before fresh consent"));write("accept-peer",Map.of());await(c,()->committed.get()!=null,"Actual released then pressed peer crouch accepts on server");
    server.runOnServer(s->{var e=committed.get();var h=s.getPlayerList().getPlayer(host);var p=s.getPlayerList().getPlayer(peer);check(e.donor().equals(host)&&e.target().equals(peer)&&e.debit()==22&&e.gain()==16,"Genuine completed transaction loses six mana between exact participating UUIDs");check(Spellbooks.mana(h)==e.donorBefore()-22&&Spellbooks.mana(p)==e.targetBefore()+16,"Two actual attachment writes match admission snapshot");check(Manabraid.active()==0&&h.getAttachedOrElse(Manabraid.DONOR_READY,0L)>s.overworld().getGameTime()&&p.getAttachedOrElse(Manabraid.RECEIVE_READY,0L)>s.overworld().getGameTime(),"Successful finite transfer consumes offer and records both actual rests");donorRest=h.getAttachedOrElse(Manabraid.DONOR_READY,0L);receiverRest=p.getAttachedOrElse(Manabraid.RECEIVE_READY,0L);});
    c.waitTicks(22);server.runOnServer(s->check(transferCount.get()==1&&Manabraid.active()==0&&Spellbooks.mana(s.getPlayerList().getPlayer(host))==wovenBefore-price-22&&Spellbooks.mana(s.getPlayerList().getPlayer(peer))==16,"Actual woven Echo cannot donate twice or renew a consumed offer"));
    c.waitFor(mc->CampConcordClient.accepted(CampConcordFx.TRANSFER)>0,120);c.takeScreenshot("manabraid_two_clients_full_host");write("verify-peer",Map.of());await(c,()->exists("peer-verified"),"Actual other renderer verifies own receipt in Minimal");
    // A watch packet belongs only to its owner; the peer is a real nonrecipient here.
    waitReady(c,server,host);server.runOnServer(s->{var h=s.getPlayerList().getPlayer(host);check(SpellCaster.edit(h,0,List.of(Runes.TOUCH.id(),"wildercord:watchweft"))==null,"Edit real private camp watch");});c.runOnClient(mc->{var d=new net.minecraft.world.phys.Vec3(.5,100.999,2.5).subtract(mc.player.getEyePosition());mc.player.setYRot((float)Math.toDegrees(Math.atan2(-d.x,d.z)));mc.player.setXRot((float)-Math.toDegrees(Math.atan2(d.y,d.horizontalDistance())));});c.waitTicks(5);cast(c);c.waitFor(mc->CampConcordClient.accepted(CampConcordFx.ARM)>0,120);write("private-watch",Map.of());await(c,()->exists("peer-private"),"Real other TCP client receives no private Watch arm");
    persistence(c,server,host,peer);
    write("disconnect-peer",Map.of());await(c,()->exists("peer-disconnected")&&server.computeOnServer(s->s.getPlayerList().getPlayers().size()==1),"Actual peer disconnect clears ownership");server.runOnServer(s->check(Manabraid.active()==0,"No departed gift owner cache"));write("host-camp-passed",Map.of("host",host.toString(),"peer",peer.toString()));write("host-passed",Map.of());
   }finally{server.runOnServer(s->{current(original);ManabraidFaultCases.clear();try{observation.close();}catch(Exception e){throw new AssertionError(e);}});c.runOnClient(mc->{MagicQuality.own=oldQuality.get(0);MagicQuality.others=oldQuality.get(1);});}
  }
 }
 private void peer(ClientGameTestContext c){await(c,()->exists("host-ready"),"Actual host address");var ready=read("host-ready");String address="127.0.0.1:"+Integer.parseInt(ready.getProperty("port"));var quality=c.computeOnClient(mc->List.of(MagicQuality.own,MagicQuality.others));boolean shift=c.computeOnClient(mc->mc.options.keyShift.isDown());
  try{c.runOnClient(mc->ConnectScreen.startConnecting(mc.gui.screen(),mc,ServerAddress.parseString(address),new ServerData("Camp concord",address,ServerData.Type.OTHER),false,null));c.waitFor(mc->mc.player!=null&&mc.level!=null&&mc.getConnection()!=null,2400);UUID id=c.computeOnClient(mc->mc.player.getUUID());write("peer-connected",Map.of("uuid",id.toString(),"pid",""+ProcessHandle.current().pid()));
   await(c,()->exists("hold-peer"),"Host asks actual held input before offer");c.runOnClient(mc->{mc.gui.setScreen(null);MagicQuality.own=MagicQuality.Level.FULL;MagicQuality.others=MagicQuality.Level.MINIMAL;});c.getInput().holdKey(o->o.keyShift);c.waitTicks(5);write("peer-held",Map.of());c.waitFor(mc->mc.level.getPlayerByUUID(UUID.fromString(ready.getProperty("uuid")))!=null,240);write("peer-saw-host",Map.of());await(c,()->exists("capacity-peer"),"Positive pending offer capacity fixture");c.getInput().releaseKey(o->o.keyShift);c.waitTicks(5);c.getInput().holdKey(o->o.keyShift);c.waitTicks(5);c.getInput().releaseKey(o->o.keyShift);write("peer-capacity-edge",Map.of());await(c,()->exists("hold-expiry-peer"),"Host completed actual capacity refusal");c.getInput().holdKey(o->o.keyShift);c.waitTicks(5);write("peer-expiry-held",Map.of());await(c,()->exists("fault-accept-peer"),"Actual pre-crouched offer expires before callback fault payment");c.getInput().releaseKey(o->o.keyShift);c.waitTicks(5);c.getInput().holdKey(o->o.keyShift);c.waitTicks(5);c.getInput().releaseKey(o->o.keyShift);c.waitTicks(3);check(c.computeOnClient(mc->CampConcordClient.accepted(CampConcordFx.TRANSFER)==0),"Claim-refused actual consent has no successful recipient transport");write("peer-fault-edge",Map.of());await(c,()->exists("accept-peer"),"New separate payment after refused gift");c.getInput().releaseKey(o->o.keyShift);c.waitTicks(5);c.getInput().holdKey(o->o.keyShift);c.waitTicks(5);c.getInput().releaseKey(o->o.keyShift);
   await(c,()->exists("verify-peer"),"Host observes actual resources");c.waitFor(mc->CampConcordClient.accepted(CampConcordFx.TRANSFER)>0&&Spellbooks.mana(mc.player)==16,120);c.takeScreenshot("manabraid_two_clients_minimal_peer");write("peer-verified",Map.of());await(c,()->exists("private-watch"),"Host's actual private watch");c.waitTicks(15);check(c.computeOnClient(mc->CampConcordClient.accepted(CampConcordFx.ARM)==0),"Actual other TCP client never receives host-only watch body");write("peer-private",Map.of());await(c,()->exists("respawn-peer"),"Host supplied actual vanilla recipient death");c.waitFor(mc->mc.player!=null&&mc.player.isDeadOrDying(),240);c.runOnClient(mc->mc.player.respawn());c.waitFor(mc->mc.player!=null&&mc.player.isAlive()&&!(mc.gui.screen() instanceof DeathScreen),240);write("peer-respawned",Map.of());await(c,()->exists("reload-peer"),"Host observed real death-copy rest");c.runOnClient(mc->mc.disconnect(new TitleScreen(),false));c.waitFor(mc->mc.player==null&&mc.level==null,240);write("peer-reload-left",Map.of());await(c,()->exists("rejoin-peer"),"Host confirms prior profile actually disconnected and saved");c.runOnClient(mc->ConnectScreen.startConnecting(mc.gui.screen(),mc,ServerAddress.parseString(address),new ServerData("Camp saved profile",address,ServerData.Type.OTHER),false,null));c.waitFor(mc->mc.player!=null&&mc.level!=null&&mc.getConnection()!=null,2400);check(c.computeOnClient(mc->mc.player.getUUID().equals(id)),"Reconnected actual profile identity is unchanged");write("peer-reloaded",Map.of());await(c,()->exists("disconnect-peer"),"Owner decides departure after completed receipt");c.runOnClient(mc->mc.disconnect(new TitleScreen(),false));c.waitFor(mc->mc.player==null&&mc.level==null,300);write("peer-disconnected",Map.of());write("peer-passed",Map.of());await(c,()->exists("host-passed"),"Host final acceptance");
  }finally{c.runOnClient(mc->{mc.options.keyShift.setDown(shift);MagicQuality.own=quality.get(0);MagicQuality.others=quality.get(1);});}
 }
 private void departures(ClientGameTestContext c,TestServerContext server,UUID host,UUID peer){
  for(String scenario:List.of("range","cord","world")){
   waitReady(c,server,host);c.waitFor(mc->mc.level.getPlayerByUUID(peer)!=null,240);aim(c,peer);float before=server.computeOnServer(s->Spellbooks.mana(s.getPlayerList().getPlayer(host)));cast(c);c.waitTicks(8);
   ItemStack cord=server.computeOnServer(s->{check(Manabraid.active()==1,"Real paid eligible pending offer exists before "+scenario+" departure");var p=s.getPlayerList().getPlayer(peer);var original=Spellbooks.cord(p);
    switch(scenario){case "range"->p.teleportTo(s.overworld(),30.5,101,.5,Set.<Relative>of(),90,0,false);case "cord"->Spellbooks.setCord(p,original.copy());case "world"->p.teleportTo(s.getLevel(net.minecraft.world.level.Level.NETHER),.5,101,.5,Set.<Relative>of(),90,0,false);}return original;});
   c.waitTicks(5);server.runOnServer(s->{var h=s.getPlayerList().getPlayer(host);var p=s.getPlayerList().getPlayer(peer);check(Manabraid.active()==0&&committed.get()==null&&Spellbooks.mana(h)==before-price&&Spellbooks.mana(p)==0,"Genuine pending "+scenario+" departure cancels without donation/refund or invalid decline geometry");check(h.getAttachedOrElse(Manabraid.DONOR_READY,0L)==0&&p.getAttachedOrElse(Manabraid.RECEIVE_READY,0L)==0,"Departed offer cannot create successful saved rests");Spellbooks.setCord(p,cord);p.teleportTo(s.overworld(),2.5,101,.5,Set.<Relative>of(),90,0,false);});c.waitTicks(12);
  }
 }
 private void persistence(ClientGameTestContext c,TestServerContext server,UUID host,UUID peer){
  // Actual vanilla damage/death and the connected client's respawn packet, never copied attachments/pose flags.
  ServerPlayer prior=server.computeOnServer(s->{var p=s.getPlayerList().getPlayer(peer);check(p.getAttachedOrElse(Manabraid.RECEIVE_READY,0L)==receiverRest,"Original real receiving rest survives quiet delay");p.hurtServer(p.level(),p.damageSources().genericKill(),Float.MAX_VALUE);check(!p.isAlive(),"Native supplied control damage actually kills recipient");return p;});write("respawn-peer",Map.of());await(c,()->exists("peer-respawned"),"Actual peer respawn packet");server.runOnServer(s->{var p=s.getPlayerList().getPlayer(peer);check(p!=prior&&p.isAlive()&&p.getAttachedOrElse(Manabraid.RECEIVE_READY,0L)==receiverRest,"Real respawn body received exact successful receiving rest through death-copy attachment policy");check(s.getPlayerList().getPlayer(host).getAttachedOrElse(Manabraid.DONOR_READY,0L)==donorRest,"Donor successful rest remains exact");s.getPlayerList().saveAll();});
  ServerPlayer priorDonor=server.computeOnServer(s->{var h=s.getPlayerList().getPlayer(host);h.hurtServer(h.level(),h.damageSources().genericKill(),Float.MAX_VALUE);check(!h.isAlive(),"Actual control damage kills donor before death-copy test");return h;});c.waitFor(mc->mc.player!=null&&mc.player.isDeadOrDying(),240);c.runOnClient(mc->mc.player.respawn());c.waitFor(mc->mc.player!=null&&mc.player.isAlive()&&!(mc.gui.screen() instanceof DeathScreen),240);server.runOnServer(s->{var h=s.getPlayerList().getPlayer(host);check(h!=priorDonor&&h.isAlive()&&h.getAttachedOrElse(Manabraid.DONOR_READY,0L)==donorRest,"Actual new connected donor body retains the exact successful rest through death-copy");s.getPlayerList().saveAll();});
  write("reload-peer",Map.of());await(c,()->exists("peer-reload-left")&&server.computeOnServer(s->s.getPlayerList().getPlayer(peer)==null),"Actual saved recipient leaves server");write("rejoin-peer",Map.of());await(c,()->exists("peer-reloaded")&&server.computeOnServer(s->s.getPlayerList().getPlayer(peer)!=null),"Same actual TCP profile reopens saved player data");server.runOnServer(s->{var p=s.getPlayerList().getPlayer(peer);check(p!=prior&&p.getAttachedOrElse(Manabraid.RECEIVE_READY,0L)==receiverRest&&s.getPlayerList().getPlayer(host).getAttachedOrElse(Manabraid.DONOR_READY,0L)==donorRest,"Saved resource-rest values survive actual disk-backed disconnect/reconnect without a historical offer");check(Manabraid.active()==0,"No offer is deserialized or recreated");});
  ServerPlayer beforeReload=server.computeOnServer(s->s.getPlayerList().getPlayer(host));connections.close();c.waitFor(mc->mc.player==null&&mc.level==null,240);await(c,()->server.computeOnServer(s->s.getPlayerList().getPlayer(host)==null),"Actual donor profile disconnect saves successful rest");connections.adopt(((TestDedicatedServerContext)server).connect());connections.current().waitForChunksDownload();connections.current().waitForClientboundPackets();check(c.computeOnClient(mc->mc.player.getUUID().equals(host)),"Real reconnected donor profile has unchanged identity");server.runOnServer(s->{var h=s.getPlayerList().getPlayer(host);check(h!=beforeReload&&h.getAttachedOrElse(Manabraid.DONOR_READY,0L)==donorRest&&s.getPlayerList().getPlayer(peer).getAttachedOrElse(Manabraid.RECEIVE_READY,0L)==receiverRest,"Both successful rest attachments survived genuine disk-backed player-data reopen; no supplied attachment copy");check(Manabraid.active()==0,"Historical offer remains absent after both saved profile reloads");});
 }
 // Own exactly the current Fabric wrapper. Closing the prior wrapper is the actual reload departure.
 // The outer resource closes the replacement once and suppresses cleanup errors behind a primary test failure.
 private static final class ConnectionOwner implements AutoCloseable {
  private TestDedicatedServerConnection current;
  ConnectionOwner(TestDedicatedServerConnection initial){adopt(initial);}
  TestDedicatedServerConnection current(){check(current!=null,"An actual current test connection is owned");return current;}
  void adopt(TestDedicatedServerConnection next){check(current==null&&next!=null,"Previous wrapper must be closed before adopting the reconnect");current=next;}
  @Override public void close(){var previous=current;if(previous==null)return;current=null;previous.close();}
 }
 private RuneDef learnManaWeave(ClientGameTestContext c,TestServerContext server,UUID host){
  var expected=WovenRunes.bind(Runes.MANABRAID,Runes.HEAL);var at=new BlockPos(3,101,3);
  int before=server.computeOnServer(s->{var h=s.getPlayerList().getPlayer(host);check(!Spellbooks.knows(h,expected.id()),"Expected woven result has not been supplied as learned");h.setExperienceLevels(50);s.overworld().setBlockAndUpdate(at,dev.wildercord.content.WildercordBlocks.FUSION_ALTAR.defaultBlockState());h.openMenu(s.overworld().getBlockState(at).getMenuProvider(s.overworld(),at));return h.experienceLevel;});
  c.waitFor(mc->mc.player.containerMenu instanceof dev.wildercord.menu.FusionAltarMenu,120);
  server.runOnServer(s->{var menu=(dev.wildercord.menu.FusionAltarMenu)s.getPlayerList().getPlayer(host).containerMenu;menu.getSlot(0).set(dev.wildercord.content.RuneItem.stack(Runes.MANABRAID));menu.getSlot(1).set(dev.wildercord.content.RuneItem.stack(Runes.HEAL));menu.getSlot(dev.wildercord.menu.FusionAltarMenu.CATALYST).set(new ItemStack(net.minecraft.world.item.Items.AMETHYST_BLOCK));menu.broadcastChanges();});
  c.waitFor(mc->dev.wildercord.content.RuneItem.runeOf(mc.player.containerMenu.getSlot(0).getItem()).map(r->r.id().equals(Runes.MANABRAID.id())).orElse(false)&&mc.player.containerMenu.getSlot(dev.wildercord.menu.FusionAltarMenu.CATALYST).getItem().is(net.minecraft.world.item.Items.AMETHYST_BLOCK),120);
  c.runOnClient(mc->mc.gameMode.handleInventoryButtonClick(mc.player.containerMenu.containerId,dev.wildercord.menu.FusionAltarMenu.BUTTON_FUSE));c.waitTicks(4);
  server.runOnServer(s->{var h=s.getPlayerList().getPlayer(host);var menu=(dev.wildercord.menu.FusionAltarMenu)h.containerMenu;check(h.experienceLevel==before-Fusions.COMBINE_XP&&menu.getSlot(0).getItem().isEmpty()&&menu.getSlot(1).getItem().isEmpty()&&menu.getSlot(dev.wildercord.menu.FusionAltarMenu.CATALYST).getItem().isEmpty(),"Real Survival Fuse pays XP and consumes source inputs exactly once");check(dev.wildercord.content.RuneItem.runeOf(menu.getSlot(dev.wildercord.menu.FusionAltarMenu.RESULT).getItem()).map(r->r.id().equals(expected.id())).orElse(false),"Actual Fuse produces exact expected woven identity");});
  c.waitFor(mc->dev.wildercord.content.RuneItem.runeOf(mc.player.containerMenu.getSlot(dev.wildercord.menu.FusionAltarMenu.RESULT).getItem()).map(r->r.id().equals(expected.id())).orElse(false),120);
  c.takeScreenshot("manabraid_two_clients_actual_altar_weave");c.runOnClient(mc->mc.gameMode.handleContainerInput(mc.player.containerMenu.containerId,dev.wildercord.menu.FusionAltarMenu.RESULT,0,net.minecraft.world.inventory.ContainerInput.QUICK_MOVE,mc.player));c.waitTicks(4);
  server.runOnServer(s->{var h=s.getPlayerList().getPlayer(host);check(h.containerMenu.getSlot(dev.wildercord.menu.FusionAltarMenu.RESULT).getItem().isEmpty(),"Real client takes genuine altar output");ItemStack found=null;for(int i=0;i<36;i++){var item=h.getInventory().getItem(i);if(dev.wildercord.content.RuneItem.runeOf(item).map(r->r.id().equals(expected.id())).orElse(false)){check(found==null&&item.getCount()==1,"One output exists after actual pickup");found=item;h.getInventory().setItem(i,ItemStack.EMPTY);}}check(found!=null,"Genuine earned output reaches player inventory");h.setItemInHand(net.minecraft.world.InteractionHand.MAIN_HAND,found);h.closeContainer();h.inventoryMenu.broadcastChanges();});
  c.waitFor(mc->dev.wildercord.content.RuneItem.runeOf(mc.player.getMainHandItem()).map(r->r.id().equals(expected.id())).orElse(false),120);c.runOnClient(mc->{mc.gui.setScreen(null);mc.gameMode.useItem(mc.player,net.minecraft.world.InteractionHand.MAIN_HAND);});c.waitTicks(4);
  server.runOnServer(s->{var h=s.getPlayerList().getPlayer(host);check(Spellbooks.knows(h,expected.id())&&h.getMainHandItem().isEmpty(),"Actual Rune use learns and consumes earned weave");s.overworld().setBlockAndUpdate(at,Blocks.AIR.defaultBlockState());});return expected;
 }
 private static void prepare(ServerPlayer p){p.setGameMode(GameType.SURVIVAL);p.getInventory().clearContent();p.setHealth(p.getMaxHealth());Spellbooks.setCord(p,new ItemStack(dev.wildercord.content.WildercordItems.ECHO_CORD));var book=Spellbooks.get(p).withStarterGiven();for(var r:List.of(Runes.TOUCH,Runes.ECHO,Runes.get("wildercord:manabraid").orElseThrow(),Runes.get("wildercord:watchweft").orElseThrow()))book=book.learn(r.id());Spellbooks.set(p,book);}
 private static void cast(ClientGameTestContext c){c.runOnClient(mc->{mc.gui.setScreen(null);ClientPlayNetworking.send(new dev.wildercord.net.WildercordNetworking.CastSpell(0));});}
 private static void waitReady(ClientGameTestContext c,TestServerContext s,UUID p){int ticks=s.computeOnServer(server->(int)Math.max(1,Spellbooks.readyAt(server.getPlayerList().getPlayer(p),0)-server.overworld().getGameTime()+1));c.waitTicks(ticks);}
 @SuppressWarnings("unchecked") private static <T>T copy(T record,Map<String,Object> changes){try{var parts=record.getClass().getRecordComponents();var types=new Class<?>[parts.length];var args=new Object[parts.length];for(int i=0;i<parts.length;i++){types[i]=parts[i].getType();args[i]=changes.getOrDefault(parts[i].getName(),parts[i].getAccessor().invoke(record));}return (T)record.getClass().getDeclaredConstructor(types).newInstance(args);}catch(ReflectiveOperationException e){throw new AssertionError(e);}}
 private static void current(dev.wildercord.config.WildercordConfig config){try{var field=dev.wildercord.config.Config.class.getDeclaredField("current");field.setAccessible(true);field.set(null,config);}catch(ReflectiveOperationException e){throw new AssertionError(e);}}
 // Fabric connect() uses the configured port; port0 does not expose the OS-assigned bound port.
 private static int localPort(){try(var socket=new java.net.ServerSocket(0,1,java.net.InetAddress.getLoopbackAddress())){return socket.getLocalPort();}catch(java.io.IOException failure){throw new AssertionError("Could not reserve local test port",failure);}}
 private static InetSocketAddress tcp(ServerPlayer p){check(p.connection.getRemoteAddress() instanceof InetSocketAddress,"Connected profile has actual network socket rather than fabricated/memory guest");var address=(InetSocketAddress)p.connection.getRemoteAddress();check(address.getAddress().isLoopbackAddress()&&address.getPort()>0,"Actual client connection is local loopback TCP");return address;}
 private static void aim(ClientGameTestContext c,UUID other){c.runOnClient(mc->{var entity=mc.level.getPlayerByUUID(other);check(entity!=null,"Other actual connected client is present in renderer");var delta=entity.getBoundingBox().getCenter().subtract(mc.player.getEyePosition());mc.player.setYRot((float)Math.toDegrees(Math.atan2(-delta.x,delta.z)));mc.player.setXRot((float)-Math.toDegrees(Math.atan2(delta.y,delta.horizontalDistance())));});c.waitTicks(5);}
 private static void move(ClientGameTestContext c){c.runOnClient(mc->{mc.gui.setScreen(null);mc.player.setYRot(0);mc.player.setXRot(0);});try{c.getInput().holdKey(o->o.keyUp);c.waitFor(mc->mc.player!=null&&mc.player.getZ()>.9,200);}catch(Throwable failure){c.runOnClient(mc->dev.wildercord.Wildercord.LOGGER.info("TWO_CLIENT_MOVE role={} pos={} yaw={} screen={} key={}",System.getProperty("wildercord.mp.role"),mc.player.position(),mc.player.getYRot(),mc.gui.screen(),mc.options.keyUp.isDown()));throw failure;}finally{c.getInput().releaseKey(o->o.keyUp);}}
 private void await(ClientGameTestContext c,BooleanSupplier condition,String reason){long deadline=System.nanoTime()+120_000_000_000L;while(System.nanoTime()<deadline){check(!Files.exists(directory.resolve("host-failure.properties"))&&!Files.exists(directory.resolve("peer-failure.properties")),"Both independent client roles remain healthy: "+reason);if(condition.getAsBoolean())return;c.waitTicks(1);}throw new AssertionError(reason+" exceeded finite120s barrier");}
 private boolean exists(String name){Path file=directory.resolve(name+".properties");return Files.exists(file)&&nonce.equals(read(name).getProperty("nonce"));}
 private Properties read(String name){try(var input=Files.newInputStream(directory.resolve(name+".properties"))){var p=new Properties();p.load(input);check(nonce.equals(p.getProperty("nonce")),"IPC belongs to current run nonce");return p;}catch(java.io.IOException error){throw new AssertionError(error);}}
 private void write(String name,Map<String,String> values){try{Files.createDirectories(directory);var p=new Properties();p.setProperty("nonce",nonce);p.putAll(values);Path temp=directory.resolve(name+".tmp");try(var output=Files.newOutputStream(temp)){p.store(output,"Bounded local native handshake");}Files.move(temp,directory.resolve(name+".properties"),StandardCopyOption.ATOMIC_MOVE,StandardCopyOption.REPLACE_EXISTING);}catch(java.io.IOException error){throw new AssertionError(error);}}
 private static void check(boolean value,String why){if(!value)throw new AssertionError(why);}
}
