package dev.wildercord.gametest;

import net.fabricmc.fabric.api.client.gametest.v1.FabricClientGameTest;
import net.fabricmc.fabric.api.client.gametest.v1.context.*;
import net.minecraft.client.gui.screens.*;
import net.minecraft.client.multiplayer.ServerData;
import net.minecraft.client.multiplayer.resolver.ServerAddress;
import net.minecraft.core.BlockPos;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.world.entity.Relative;
import net.minecraft.world.level.GameType;
import net.minecraft.world.level.block.Blocks;
import dev.wildercord.wildlife.RooksRainshield;
import net.minecraft.world.InteractionHand;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.entity.EntitySpawnReason;
import net.minecraft.world.entity.EntityTypes;
import net.minecraft.world.entity.projectile.arrow.Arrow;
import net.minecraft.world.phys.*;
import java.net.InetSocketAddress;
import java.nio.file.*;
import java.util.*;
import java.util.function.BooleanSupplier;

/** Two real client JVMs through actual loopback TCP. Explicit crouch consent and one real cooperative arrow catch; supplied combat items, no earned acquisition claim. */
public final class WildercordTwoClientsRainshieldTest implements FabricClientGameTest {
 private Path directory;private String nonce;
 @Override public void runTest(ClientGameTestContext c){
  directory=Path.of(System.getProperty("wildercord.mp.directory")).toAbsolutePath();nonce=System.getProperty("wildercord.mp.nonce");check(nonce!=null&&!nonce.isBlank(),"Explicit per-run nonce required");
  try{if("host".equals(System.getProperty("wildercord.mp.role")))host(c);else if("peer".equals(System.getProperty("wildercord.mp.role")))peer(c);else throw new AssertionError("Explicit host/peer role required");}
  catch(Throwable error){write(System.getProperty("wildercord.mp.role")+"-failure",Map.of("error",error.toString()));throw error;}
  finally{if("peer".equals(System.getProperty("wildercord.mp.role")))c.runOnClient(mc->{if(mc.player!=null||mc.level!=null)mc.disconnect(new TitleScreen(),false);});}
 }
 private void host(ClientGameTestContext c){
  var props=new Properties();props.setProperty("server-ip","127.0.0.1");props.setProperty("server-port",Integer.toString(localPort()));props.setProperty("max-players","2");props.setProperty("white-list","false");props.setProperty("online-mode","false");props.setProperty("enforce-secure-profile","false");props.setProperty("view-distance","5");props.setProperty("simulation-distance","5");
  try(var server=c.worldBuilder().createServer(props);var connection=server.connect()){
   connection.waitForChunksDownload();connection.waitForClientboundPackets();UUID host=c.computeOnClient(mc->mc.player.getUUID());long pid=ProcessHandle.current().pid();write("host-ready",Map.of("port",Integer.toString(server.computeOnServer(s->s.getPort())),"pid",Long.toString(pid),"uuid",host.toString()));await(c,()->exists("peer-connected")&&server.computeOnServer(s->s.getPlayerList().getPlayers().size()==2),"Two actual TCP profiles join");var receipt=read("peer-connected");UUID peer=UUID.fromString(receipt.getProperty("uuid"));check(!peer.equals(host)&&Long.parseLong(receipt.getProperty("pid"))!=pid,"Distinct native JVM PIDs and UUIDs");
   server.runCommand("gamerule spawn_mobs false");server.runCommand("difficulty normal");server.runCommand("team add wc_rainshield");server.runCommand("team join wc_rainshield "+server.computeOnServer(s->s.getPlayerList().getPlayer(host).getGameProfile().name()));server.runCommand("team join wc_rainshield "+server.computeOnServer(s->s.getPlayerList().getPlayer(peer).getGameProfile().name()));
   server.runOnServer(s->{var h=s.getPlayerList().getPlayer(host);var r=s.getPlayerList().getPlayer(peer);check(!tcp(h).equals(tcp(r)),"Separate actual loopback TCP sockets");var l=s.overworld();for(int x=-10;x<=6;x++)for(int z=-4;z<=4;z++){l.setBlock(new BlockPos(x,100,z),Blocks.STONE.defaultBlockState(),2);for(int y=101;y<=105;y++)l.setBlock(new BlockPos(x,y,z),Blocks.AIR.defaultBlockState(),2);}for(var p:List.of(h,r)){p.setGameMode(GameType.SURVIVAL);dev.wildercord.player.Spellbooks.set(p,dev.wildercord.player.Spellbooks.get(p).withStarterGiven());p.getInventory().clearContent();p.setHealth(20);}h.setItemInHand(InteractionHand.MAIN_HAND,new ItemStack(RooksRainshield.ITEM));positions(h,r);});c.waitTicks(6);write("peer-stand",Map.of());await(c,()->exists("peer-standing")&&server.computeOnServer(s->!s.getPlayerList().getPlayer(peer).isShiftKeyDown()),"Actual peer withholding consent");
   interact(c,peer);c.waitTicks(3);try(var held=held(c,o->o.keyUse)){c.runOnClient(mc->mc.gameMode.useItem(mc.player,InteractionHand.MAIN_HAND));c.waitTicks(16);server.runOnServer(s->{check(!RooksRainshield.active(s.getPlayerList().getPlayer(host)),"Pending actual offer refuses cover without a fresh recipient gesture");shoot(s);});c.waitTicks(12);server.runOnServer(s->{var h=s.getPlayerList().getPlayer(host);var r=s.getPlayerList().getPlayer(peer);check(r.getHealth()<20&&h.getMainHandItem().getDamageValue()==0&&r.getAttachedOrElse(RooksRainshield.READY,0L)==0&&h.getAttachedOrElse(RooksRainshield.READY,0L)==0,"Nonconsenting actual teammate remains unprotected and neither earns cost/rest");});}
   c.waitTicks(4);server.runCommand("team leave "+server.computeOnServer(s->s.getPlayerList().getPlayer(peer).getGameProfile().name()));server.runOnServer(s->{var h=s.getPlayerList().getPlayer(host);var r=s.getPlayerList().getPlayer(peer);positions(h,r);r.setHealth(20);check(!h.isAlliedTo(r),"Actual connected recipient genuinely leaves alliance before team refusal");});interact(c,peer);c.waitTicks(3);write("peer-nonally-gesture",Map.of());await(c,()->exists("peer-nonally-crouched")&&server.computeOnServer(s->s.getPlayerList().getPlayer(peer).isShiftKeyDown()),"Actual nonallied recipient nevertheless supplies a fresh crouch gesture after interaction");
   try(var held=held(c,o->o.keyUse)){c.runOnClient(mc->mc.gameMode.useItem(mc.player,InteractionHand.MAIN_HAND));c.waitTicks(16);server.runOnServer(s->{check(RooksRainshield.active(s.getPlayerList().getPlayer(host)),"Carrier remains eligible for explicit self protection despite nonallied selection refusal");shoot(s);});c.waitTicks(12);server.runOnServer(s->{var h=s.getPlayerList().getPlayer(host);var r=s.getPlayerList().getPlayer(peer);check(r.getHealth()<20&&h.getHealth()==20&&h.getMainHandItem().getDamageValue()==0&&h.getAttachedOrElse(RooksRainshield.READY,0L)==0&&r.getAttachedOrElse(RooksRainshield.READY,0L)==0,"Fresh gesture cannot cover actual nonallied peer: real arrow harms it without catch cost/rest");});}
   write("peer-nonally-finished",Map.of());await(c,()->exists("peer-nonally-released")&&server.computeOnServer(s->!s.getPlayerList().getPlayer(peer).isShiftKeyDown()),"Peer genuinely releases negative-control gesture");server.runCommand("team join wc_rainshield "+server.computeOnServer(s->s.getPlayerList().getPlayer(peer).getGameProfile().name()));c.waitTicks(4);server.runOnServer(s->{var h=s.getPlayerList().getPlayer(host);var r=s.getPlayerList().getPlayer(peer);check(!RooksRainshield.active(h),"Actual use release closes self fan");positions(h,r);r.setHealth(20);});
   write("peer-held-before-offer",Map.of());await(c,()->exists("peer-held-at-offer")&&server.computeOnServer(s->s.getPlayerList().getPlayer(peer).isShiftKeyDown()),"Actual allied peer already holds crouch BEFORE this offer");interact(c,peer);c.waitTicks(3);
   try(var held=held(c,o->o.keyUse)){c.runOnClient(mc->mc.gameMode.useItem(mc.player,InteractionHand.MAIN_HAND));c.waitTicks(16);server.runOnServer(s->{var h=s.getPlayerList().getPlayer(host);var r=s.getPlayerList().getPlayer(peer);check(!RooksRainshield.active(h)&&h.getMainHandItem().getDamageValue()==0&&h.getAttachedOrElse(RooksRainshield.READY,0L)==0&&r.getAttachedOrElse(RooksRainshield.READY,0L)==0,"Already-held crouch cannot grant cover or cost on actual offered item use");});}
   write("peer-regesture-same-offer",Map.of());await(c,()->exists("peer-crouching")&&server.computeOnServer(s->s.getPlayerList().getPlayer(peer).isShiftKeyDown()),"Peer releases then recrouches after same finite offer; no replacement interaction renews it");c.waitTicks(3);
   long deadline;
   try(var held=held(c,o->o.keyUse)){openOnRecipient(c,peer);c.waitTicks(16);server.runOnServer(s->{var h=s.getPlayerList().getPlayer(host);check(RooksRainshield.active(h)&&h.getTicksUsingItem()>=RooksRainshield.PREP,"Actual host packets prepare cooperative fan");shoot(s);});c.waitTicks(12);deadline=server.computeOnServer(s->{var h=s.getPlayerList().getPlayer(host);var r=s.getPlayerList().getPlayer(peer);long ready=h.getAttachedOrElse(RooksRainshield.READY,0L);check(r.getHealth()==20&&h.getHealth()==20&&h.getMainHandItem().getDamageValue()==4&&!RooksRainshield.active(h),"One real frontal arrow against actual connected teammate is caught once");check(ready==r.getAttachedOrElse(RooksRainshield.READY,0L)&&ready>s.overworld().getGameTime(),"Cooperation reserves both exact matching saved deadlines");return ready;});}
   c.takeScreenshot("two_clients_rainshield_cooperative_host");write("peer-catch",Map.of());await(c,()->exists("peer-catch-seen"),"Peer observes own genuine covered health and source render");
   // Genuine recipient death-copy receipt: no synthetic player or attachment restoration.
   var departed=new ServerPlayer[1];var originalSocket=new java.net.InetSocketAddress[1];
   server.runOnServer(s->{var h=s.getPlayerList().getPlayer(host);var r=s.getPlayerList().getPlayer(peer);departed[0]=r;originalSocket[0]=tcp(r);check(r.isAlive()&&r.getAttachedOrElse(RooksRainshield.READY,0L)==deadline&&deadline>s.overworld().getGameTime(),"Recipient dies during the same real earned shared rest");check(r.hurtServer(r.level(),r.damageSources().genericKill(),Float.MAX_VALUE)&&!r.isAlive(),"Actual native fatal damage retires the connected recipient body");check(!RooksRainshield.active(h),"Spent cooperative cover remains retired at recipient death");});
   write("peer-respawn-request",Map.of());await(c,()->exists("peer-respawned")&&server.computeOnServer(s->{var r=s.getPlayerList().getPlayer(peer);return r!=null&&r!=departed[0]&&r.isAlive();}),"Actual second TCP client sends the native respawn request and replaces its server body");
   server.runOnServer(s->{var h=s.getPlayerList().getPlayer(host);var r=s.getPlayerList().getPlayer(peer);check(r!=departed[0]&&r.getUUID().equals(peer)&&r.level().getEntity(peer)==r&&tcp(r).equals(originalSocket[0]),"Same actual socket/profile now owns a distinct registered living body");check(r.getAttachedOrElse(RooksRainshield.READY,0L)==deadline&&h.getAttachedOrElse(RooksRainshield.READY,0L)==deadline&&deadline>s.overworld().getGameTime(),"Actual death-copy preserves both exact future earned shared deadlines");check(!RooksRainshield.active(h)&&!RooksRainshield.active(r)&&h.getMainHandItem().getDamageValue()==4,"Respawn inherits no fan and grants no extra price or protection");positions(h,r);});
   c.waitTicks(5);write("peer-respawn-verified",Map.of());
   // Rest expires through ordinary connected gameplay ticks; no source clock or attachment reset.
   await(c,()->server.computeOnServer(s->s.overworld().getGameTime()>=deadline),"Same earned 300-tick rest genuinely elapses");server.runOnServer(s->positions(s.getPlayerList().getPlayer(host),s.getPlayerList().getPlayer(peer)));interact(c,peer);c.waitTicks(3);write("peer-renew",Map.of());await(c,()->exists("peer-renewed")&&server.computeOnServer(s->s.getPlayerList().getPlayer(peer).isShiftKeyDown()),"Recipient makes a new crouch edge for the second real offer");c.waitTicks(3);
   try(var held=held(c,o->o.keyUse)){openOnRecipient(c,peer);c.waitTicks(16);server.runOnServer(s->check(RooksRainshield.active(s.getPlayerList().getPlayer(host)),"Second actual fan prepares only after earned rest"));write("disconnect-peer",Map.of());await(c,()->exists("peer-disconnected")&&server.computeOnServer(s->s.getPlayerList().getPlayers().size()==1),"Real recipient connection leaves during active cover");server.runOnServer(s->{var h=s.getPlayerList().getPlayer(host);check(!RooksRainshield.active(h)&&h.getMainHandItem().getDamageValue()==4&&h.getAttachedOrElse(RooksRainshield.READY,0L)==deadline,"Actual disconnect cancels cover without extra cost or deadline renewal");});}
   write("host-rainshield-passed",Map.of("host",host.toString(),"peer",peer.toString()));
  }finally{write("host-closed",Map.of());}
 }
 private void peer(ClientGameTestContext c){
  await(c,()->exists("host-ready"),"Host publishes genuine TCP port");var ready=read("host-ready");int port=Integer.parseInt(ready.getProperty("port"));check(port>0,"Positive actual listener port");UUID host=UUID.fromString(ready.getProperty("uuid"));c.runOnClient(mc->{var data=new ServerData("Local Rainshield", "127.0.0.1:"+port,ServerData.Type.OTHER);ConnectScreen.startConnecting(new TitleScreen(),mc,ServerAddress.parseString("127.0.0.1:"+port),data,false,null);});c.waitFor(mc->mc.player!=null&&mc.level!=null,1200);write("peer-connected",Map.of("uuid",c.computeOnClient(mc->mc.player.getUUID().toString()),"pid",Long.toString(ProcessHandle.current().pid())));await(c,()->exists("peer-stand"),"Host supplies supported combat scene");c.runOnClient(mc->mc.gui.setScreen(null));write("peer-standing",Map.of());await(c,()->exists("peer-nonally-gesture"),"Host isolates actual nonallied recipient");
  try(var negative=held(c,o->o.keyShift)){c.waitTicks(4);write("peer-nonally-crouched",Map.of());await(c,()->exists("peer-nonally-finished"),"Real nonallied arrow control finishes");}c.waitTicks(4);write("peer-nonally-released",Map.of());
  await(c,()->exists("peer-held-before-offer"),"Host requests actual pre-held allied input");try(var prior=held(c,o->o.keyShift)){c.waitTicks(4);write("peer-held-at-offer",Map.of());await(c,()->exists("peer-regesture-same-offer"),"Actual already-held refusal observed");}c.waitTicks(4);
  try(var crouch=held(c,o->o.keyShift)){c.waitTicks(4);write("peer-crouching",Map.of());await(c,()->exists("peer-catch"),"Actual consent leads to actual peer cover");check(c.computeOnClient(mc->mc.player.getHealth()==20),"Actual recipient client receives unchanged covered health");c.takeScreenshot("two_clients_rainshield_cooperative_peer");write("peer-catch-seen",Map.of());}
  await(c,()->exists("peer-respawn-request"),"Host delivers actual fatal damage during earned shared rest");var formerBody=c.computeOnClient(mc->mc.player);c.waitFor(mc->mc.player!=null&&mc.player.isDeadOrDying(),240);c.runOnClient(mc->mc.player.respawn());c.waitFor(mc->mc.player!=null&&mc.player!=formerBody&&mc.player.isAlive()&&!(mc.gui.screen() instanceof DeathScreen),240);check(c.computeOnClient(mc->mc.player.getUUID().toString().equals(read("peer-connected").getProperty("uuid"))),"Native respawn retains the actual connected profile UUID");c.runOnClient(mc->mc.gui.setScreen(null));write("peer-respawned",Map.of());await(c,()->exists("peer-respawn-verified"),"Host verifies actual server body replacement and saved shared rest");
  await(c,()->exists("peer-renew"),"Carrier makes a new offer after real elapsed rest");try(var renewed=held(c,o->o.keyShift)){c.waitTicks(4);write("peer-renewed",Map.of());await(c,()->exists("disconnect-peer"),"Second fan starts after fresh consent");c.runOnClient(mc->mc.disconnect(new TitleScreen(),false));c.waitFor(mc->mc.player==null&&mc.level==null,200);write("peer-disconnected",Map.of());}
  await(c,()->exists("host-closed"),"Host tears down dedicated world finitely");
 }
 private static void positions(ServerPlayer h,ServerPlayer r){h.teleportTo(h.level(),.5,101,.5,Set.<Relative>of(),90,0,false);r.teleportTo(r.level(),-1.5,101,.5,Set.<Relative>of(),90,0,false);}
 private static void shoot(net.minecraft.server.MinecraftServer s){var a=EntityTypes.ARROW.create(s.overworld(),EntitySpawnReason.COMMAND);check(a!=null,"Actual vanilla projectile");a.snapTo(-5.5,102.1,.5,0,0);a.setDeltaMovement(new Vec3(.65,0,0));a.setBaseDamage(2);s.overworld().addFreshEntity(a);}
 private static void interact(ClientGameTestContext c,UUID recipient){aim(c,recipient);c.runOnClient(mc->{var r=mc.level.getPlayerByUUID(recipient);check(r!=null,"Actual remote profile renderer");mc.gameMode.interact(mc.player,r,new EntityHitResult(r,r.getBoundingBox().getCenter()),InteractionHand.MAIN_HAND);});}
 private static void openOnRecipient(ClientGameTestContext c,UUID recipient){c.runOnClient(mc->{var r=mc.level.getPlayerByUUID(recipient);check(r!=null,"Actual selected connected ally remains present for entity-use opening");mc.gameMode.interact(mc.player,r,new EntityHitResult(r,r.getBoundingBox().getCenter()),InteractionHand.MAIN_HAND);});}
 private static int localPort(){try(var socket=new java.net.ServerSocket(0,1,java.net.InetAddress.getLoopbackAddress())){return socket.getLocalPort();}catch(java.io.IOException failure){throw new AssertionError("Could not reserve local test port",failure);}}
 private static InetSocketAddress tcp(ServerPlayer p){check(p.connection.getRemoteAddress() instanceof InetSocketAddress,"Connected profile has actual network socket rather than fabricated/memory guest");var address=(InetSocketAddress)p.connection.getRemoteAddress();check(address.getAddress().isLoopbackAddress()&&address.getPort()>0,"Actual client connection is local loopback TCP");return address;}
 private static void aim(ClientGameTestContext c,UUID other){c.runOnClient(mc->{var entity=mc.level.getPlayerByUUID(other);check(entity!=null,"Other actual connected client is present in renderer");var delta=entity.getBoundingBox().getCenter().subtract(mc.player.getEyePosition());mc.player.setYRot((float)Math.toDegrees(Math.atan2(-delta.x,delta.z)));mc.player.setXRot((float)-Math.toDegrees(Math.atan2(delta.y,delta.horizontalDistance())));});c.waitTicks(5);}
 private static void move(ClientGameTestContext c){c.runOnClient(mc->{mc.gui.setScreen(null);mc.player.setYRot(0);mc.player.setXRot(0);});try{c.getInput().holdKey(o->o.keyUp);c.waitFor(mc->mc.player!=null&&mc.player.getZ()>.9,200);}catch(Throwable failure){c.runOnClient(mc->dev.wildercord.Wildercord.LOGGER.info("TWO_CLIENT_MOVE role={} pos={} yaw={} screen={} key={}",System.getProperty("wildercord.mp.role"),mc.player.position(),mc.player.getYRot(),mc.gui.screen(),mc.options.keyUp.isDown()));throw failure;}finally{c.getInput().releaseKey(o->o.keyUp);}}
 private void await(ClientGameTestContext c,BooleanSupplier condition,String reason){long deadline=System.nanoTime()+120_000_000_000L;while(System.nanoTime()<deadline){check(!Files.exists(directory.resolve("host-failure.properties"))&&!Files.exists(directory.resolve("peer-failure.properties")),"Both independent client roles remain healthy: "+reason);if(condition.getAsBoolean())return;c.waitTicks(1);}throw new AssertionError(reason+" exceeded finite120s barrier");}
 private boolean exists(String name){Path file=directory.resolve(name+".properties");return Files.exists(file)&&nonce.equals(read(name).getProperty("nonce"));}
 private Properties read(String name){try(var input=Files.newInputStream(directory.resolve(name+".properties"))){var p=new Properties();p.load(input);check(nonce.equals(p.getProperty("nonce")),"IPC belongs to current run nonce");return p;}catch(java.io.IOException error){throw new AssertionError(error);}}
 private void write(String name,Map<String,String> values){try{Files.createDirectories(directory);var p=new Properties();p.setProperty("nonce",nonce);p.putAll(values);Path temp=directory.resolve(name+".tmp");try(var output=Files.newOutputStream(temp)){p.store(output,"Bounded local native handshake");}Files.move(temp,directory.resolve(name+".properties"),StandardCopyOption.ATOMIC_MOVE,StandardCopyOption.REPLACE_EXISTING);}catch(java.io.IOException error){throw new AssertionError(error);}}
 private static void check(boolean value,String why){if(!value)throw new AssertionError(why);}
 private static KeyHold held(ClientGameTestContext c,java.util.function.Function<net.minecraft.client.Options,net.minecraft.client.KeyMapping> key){return new KeyHold(c,key);}
 private static final class KeyHold implements AutoCloseable {
  private final ClientGameTestContext c;private final java.util.function.Function<net.minecraft.client.Options,net.minecraft.client.KeyMapping> key;
  KeyHold(ClientGameTestContext c,java.util.function.Function<net.minecraft.client.Options,net.minecraft.client.KeyMapping> key){this.c=c;this.key=key;c.getInput().holdKey(key);}
  @Override public void close(){c.getInput().releaseKey(key);}
 }
}
