"""0.13 mana elixirs: Torrent, Deep Well and Condensing. Their names, status icons and brewing recipes.

The numbers live in src/main/java/dev/wildercord/player/ElixirRules.java; the effects in content/WildercordEffects.java.
Each brews from a residue harvest (see world/ResidueRules.java), so the elixirs tie mana to the marks big spells leave.
"""
from item_art import Canvas, blit, hexc

ELIXIRS = {
    # id: (name, brewed from, reagent)
    'torrent': ('Torrent', 'wildercord:clarity', 'wildercord:bottled_gale'),
    'deep_well': ('the Deep Well', 'minecraft:awkward', 'wildercord:geode_grit'),
    'condensing': ('Condensing', 'minecraft:awkward', 'wildercord:hourglass_sand'),
}
EFFECT_NAMES = {'torrent': 'Torrent', 'deep_well': 'Deep Well', 'condensing': 'Condensing'}

LANG = {}
for _id, (_name, _from, _reagent) in ELIXIRS.items():
    LANG[f'effect.wildercord.{_id}'] = EFFECT_NAMES[_id]
    LANG[f'item.minecraft.potion.effect.wildercord_{_id}'] = f'Elixir of {_name}'
    LANG[f'item.minecraft.splash_potion.effect.wildercord_{_id}'] = f'Splash Elixir of {_name}'
    LANG[f'item.minecraft.lingering_potion.effect.wildercord_{_id}'] = f'Lingering Elixir of {_name}'
    LANG[f'item.minecraft.tipped_arrow.effect.wildercord_{_id}'] = f'Arrow of {_name}'

# Status icons, 18x18. Torrent: a mana drop pouring down in streaks.
TORRENT = """
..................
.......o..........
......oLo....o....
.....oLlLo..oLo...
....oLllMo..oLo...
....oLlMMo...o....
.....oMMo.........
......oo...o......
..o.......oLo.....
.oLo.....oLlLo....
.oLo....oLllMo....
..o.....oLlMMo....
.........oMMo.....
....o.....oo......
...oLo............
...oLo............
....o.............
..................
"""
TORRENT_PAL = {'o': hexc('#1A4A6A'), 'L': hexc('#C8F4FF'), 'l': hexc('#7AD8F8'), 'M': hexc('#3A9AD0')}

# Deep Well: a stone well ring with deep blue mana far down in it.
DEEP_WELL = """
..................
..................
....oooooooooo....
...osSSSSSSSSso...
..osSoooooooSSso..
..oSo.mmmmmm.oSo..
..oSomMMMMMMmoSo..
..oSomMDDDDMmoSo..
..oSomMDwwDMmoSo..
..oSomMDDDDMmoSo..
..oSomMMMMMMmoSo..
..oSo.mmmmmm.oSo..
..osSoooooooSSso..
...osSSSSSSSSso...
....oooooooooo....
..................
..................
..................
"""
DEEP_WELL_PAL = {'o': hexc('#24222E'), 'S': hexc('#8C8A96'), 's': hexc('#C4C2CC'), 'm': hexc('#2A3080'),
                 'M': hexc('#3A4AB0'), 'D': hexc('#6A7AE8'), 'w': hexc('#D8E0FF')}

# Condensing: mana motes drawn into a bright golden ring.
CONDENSING = """
..................
..y.............y.
...y...........y..
..................
......oooooo......
.....oGGGGGGo.....
....oGgo..oGGo....
....oGo....oGo....
y...oGo.WW.oGo...y
....oGo.WW.oGo....
....oGo....oGo....
....oGGo..ogGo....
.....oGGGGGGo.....
......oooooo......
..................
...y...........y..
..y.............y.
..................
"""
CONDENSING_PAL = {'o': hexc('#6A4A10'), 'G': hexc('#F0C860'), 'g': hexc('#FFF0B0'), 'W': hexc('#FFFFFF'),
                  'y': hexc('#D8A8FF')}


def icon(text, pal):
    cv = Canvas(18)
    blit(cv, text, pal)
    return cv.image()


ICONS = {'torrent': (TORRENT, TORRENT_PAL), 'deep_well': (DEEP_WELL, DEEP_WELL_PAL), 'condensing': (CONDENSING, CONDENSING_PAL)}


def write(g):
    for eid, (text, pal) in ICONS.items():
        g.save(icon(text, pal), g.ASSETS / f'textures/mob_effect/{eid}.png')
    for container in ('potion', 'splash_potion', 'lingering_potion'):
        item = f'minecraft:{container}'
        for eid, (_name, potion_in, reagent) in ELIXIRS.items():
            short = potion_in.split(':')[1]
            g.brewing(f'{container}_{short}_{reagent.split(":")[1]}', item, potion_in, reagent, item, f'wildercord:{eid}')
            g.brewing(f'{container}_{eid}_redstone', item, f'wildercord:{eid}', 'minecraft:redstone', item, f'wildercord:long_{eid}')
            g.brewing(f'{container}_{eid}_glowstone_dust', item, f'wildercord:{eid}', 'minecraft:glowstone_dust', item, f'wildercord:strong_{eid}')
    for eid in ELIXIRS:
        for potion in (eid, f'long_{eid}', f'strong_{eid}'):
            g.brewing(f'potion_{potion}_gunpowder', 'minecraft:potion', f'wildercord:{potion}', 'minecraft:gunpowder', 'minecraft:splash_potion', f'wildercord:{potion}')
            g.brewing(f'splash_potion_{potion}_dragon_breath', 'minecraft:splash_potion', f'wildercord:{potion}', 'minecraft:dragon_breath', 'minecraft:lingering_potion', f'wildercord:{potion}')
