"""Masters of Tomorrow language and its spawn egg, generated with the existing aura art pipeline."""

LANG = {
    "master.wildercord.school.ember": "Ember",
    "master.wildercord.school.gale": "Gale",
    "master.wildercord.school.stone": "Stone",
    "message.wildercord.master.first_clear": "First clear recorded: %s. Your technique lesson is permanent.",
    "message.wildercord.master.first_clear_known": "First clear recorded: %s. You already know this school's technique lesson.",
    "message.wildercord.master.record_clear": "%s: cleared",
    "message.wildercord.master.record_open": "%s: not yet cleared",
    "entity.wildercord.sword_master": "Sword Master",
    "item.wildercord.sword_master_spawn_egg": "Sword Master Spawn Egg",
    "key.category.wildercord.masters_arts": "Wildercord: Master's Arts",
    "key.wildercord.spellcut": "Spellcut",
    "key.wildercord.rising_break": "Rising Break",
    "key.wildercord.driving_cut": "Driving Cut",
    "hud.wildercord.masters_aim_left": "Strike committed left",
    "hud.wildercord.masters_aim_right": "Strike committed right",
    "hud.wildercord.masters_aim_up": "Strike committed above",
    "hud.wildercord.masters_aim_down": "Strike committed below",
    "screen.wildercord.aura.masters_help": "Master's Arts",
    "screen.wildercord.aura.masters_spellcut": "%s: Spellcut",
    "screen.wildercord.aura.masters_rising_break": "%s: Rising Break",
    "screen.wildercord.aura.masters_driving_cut": "%s: Driving Cut",
    "screen.wildercord.aura.masters_rebind": "Rebind in Options > Controls > Key Binds > Wildercord: Master's Arts",
    "aura.wildercord.art.spellcut": "Spellcut",
    "aura.wildercord.art.spellcut.desc": "Edge: after a short windup, sever up to 3 incoming hostile bolts in front and slash nearby foes. 14 aura; 3 second rest.",
    "aura.wildercord.art.rising_break": "Rising Break",
    "aura.wildercord.art.rising_break.desc": "Form: a rising blade strike wears extra stance and lifts ordinary foes. 20 aura; 5 second rest.",
    "aura.wildercord.art.driving_cut": "Driving Cut",
    "aura.wildercord.art.driving_cut.desc": "Form: a committed 5-block thrust breaks a damaged held spell, including absorption, then seals casting for 1 second. Held spells share 8-second interrupt protection. 18 aura; 4 second rest.",
    "message.wildercord.masters_art.stage": "This art opens at %s.",
    "message.wildercord.masters_art.rest": "Recovering: %s seconds remaining.",
    "message.wildercord.masters_art.aura": "This art needs %s aura.",
    "message.wildercord.master.dialogue": "%s master: This is a lethal trial for up to 8 willing challengers. Speak to me again within 10 seconds to accept. Once accepted, you have 30 seconds for others to speak and join; the challenger can use /master ready. Trials do not create a party: use /party invite <player> and /party accept <inviter> for friendly-spell protection.",
    "message.wildercord.master.challenge": "%s master: Your trial begins in 30 seconds. Others must speak twice to join. Up to 8 challengers; leaving the 24-block arena forfeits. /master ready starts early. Join a party separately for friendly-spell protection.",
    "message.wildercord.master.joined": "You joined the master's trial. The roster and difficulty lock when the fight begins.",
    "message.wildercord.master.ready": "The trial is starting.",
    "message.wildercord.master.unavailable": "Trials require a living Survival player, a non-Peaceful world and no active duel or spar.",
    "message.wildercord.master.teacher_hint": "Sneak and speak to me to ask about an endgame Master trial.",
    "message.wildercord.master.teacher_offer": "I can introduce a Master for a lethal endgame trial. Sneak and speak to me again within 10 seconds to invite them. They will wait one minute; speaking to the Master is a separate choice to join.",
    "message.wildercord.master.teacher_arrived": "The %s master is waiting nearby for one minute. Speak to them twice to accept the trial. No one has been enrolled yet.",
    "message.wildercord.master.teacher_busy": "Finish your current duel or spar first, and speak to a teacher who is not fighting or leaving.",
    "message.wildercord.master.teacher_unready": "Master trials open at Aura Form or Heart Circle VIII. Keep training with ordinary teachers first.",
    "message.wildercord.master.reserved": "This master is waiting for the player who requested the introduction. You can ask to join after they open the lobby.",
    "message.wildercord.master.occupied": "A trial is already active nearby or you are already enrolled.",
    "message.wildercord.master.obstructed": "Find clear, level ground with room for an arena.",
    "message.wildercord.master.no_trial": "No open trial nearby, or this trial already has 8 challengers.",
    "message.wildercord.master.waiting": "You are enrolled. Waiting for the challenger or the 30-second countdown.",
    "message.wildercord.master.in_progress": "This trial has begun. Its roster is locked.",
    "message.wildercord.master.victory": "You defeated the %s master.",
    "boss.wildercord.master.status": "%s Master · %s",
    "boss.wildercord.master.prepare": "%s/%s challengers · Starts in %ss",
    "boss.wildercord.master.sweep": "Sweeping cut",
    "boss.wildercord.master.thrust": "Piercing thrust",
    "boss.wildercord.master.crescent": "Crescent volley",
    "boss.wildercord.master.break_cast": "Spellbreaker thrust",
    "boss.wildercord.master.pursuit_break": "Cast pursuit: committed dash",
    "boss.wildercord.master.pursuit_strike": "Pursuit strike: sidestep or parry",
    "message.wildercord.master.pursuit_hint": "Strike in 0.4s: leave the marked lane or face the blade and parry.",
    "message.wildercord.master.pursuit_lesson": "A free master can pursue a held cast. After a cast is held for 0.3s, the dash commits to your old position, then warns before a short strike. Release, sidestep, use cover or parry. A landed hit can break your charge; a miss leaves an opening.",
    "message.wildercord.master.pursuit_ember": "Ember: up to 4.8 blocks per dash, 28 Aura, 7s between attempts. A strike or cancelled dash leaves 1.5s to counter.",
    "message.wildercord.master.pursuit_gale": "Gale: up to 6.4 blocks per dash, 26 Aura, 5s between attempts. A strike or cancelled dash leaves 1.5s to counter.",
    "message.wildercord.master.pursuit_stone": "Stone: up to 3.6 blocks per dash, 30 Aura, 8s between attempts. A strike or cancelled dash leaves 1.5s to counter.",
    "boss.wildercord.master.crosswind_reprise": "Crosswind Reprise: lateral step",
    "boss.wildercord.master.crosswind_reply": "Crosswind reply: leave the narrow lane",
    "message.wildercord.master.crosswind_hint": "Reply in 0.5s: sidestep, backstep, use cover or face the blade and parry.",
    "message.wildercord.master.gale_lesson": "Gale master: After my first attack, I may step sideways, then mark a narrow reply. I commit to your old position. Leave the lane, use cover or parry; my miss leaves 1.6s to counter. Each attempt costs 24 Aura, with at least 7s between attempts.",
    "boss.wildercord.master.stone_fracture": "Stone Fracture: fixed frontal brace",
    "boss.wildercord.master.fracture_reply": "Fracture reply: leave the narrow lane",
    "message.wildercord.master.fracture_hint": "Reply in 0.6s: sidestep, backstep, use cover or face the blade and parry.",
    "message.wildercord.master.stone_lesson": "Stone master: I plant for 0.4s, brace for 0.6s, then warn a narrow reply for 0.6s. Hit my back during the brace, break my stance or axe the guard. Leave the reply lane or parry, then counter for 2s. Each attempt costs 28 Aura, with at least 9s between attempts.",
    "boss.wildercord.master.kiln_ring": "Kiln Ring",
    "boss.wildercord.master.stone_fault_march": "Stone Fault March",
    "message.wildercord.master.march_hint": "Three ground bands strike outward. Step sideways, jump the low pulse, or move inward onto spent ground.",
    "message.wildercord.master.kiln_hint": "Step inside the blue rim, escape the outer edge, or jump over the low ring.",
    "boss.wildercord.master.cinder_wake": "Cinder Wake: leave the broad cut",
    "boss.wildercord.master.afterburn": "Afterburn: leave the marked lanes",
    "message.wildercord.master.afterburn_hint": "Afterburn in 1.3s: step out of the marked lanes.",
    "message.wildercord.master.ember_lesson": "Ember master: My broad cut leaves a narrow wake. Leave the cut, then step out of the marked lanes before they ignite. I cannot turn the wake after my first warning.",
    "boss.wildercord.master.broken": "Stance broken",
    "boss.wildercord.master.recover": "Open to counters",
    "boss.wildercord.master.guard": "Frontal spell-cut guard",
    "boss.wildercord.master.ready": "Reading the field",
    "boss.wildercord.master.breathing": "Catching breath",
}


def write(g):
    # Reuse the original authored duelist egg texture until the master has its own full art set.
    g.write_json(g.ASSETS / "models/item/sword_master_spawn_egg.json", {
        "parent": "minecraft:item/generated",
        "textures": {"layer0": "wildercord:item/duelist_spawn_egg"},
    })
    g.write_json(g.ASSETS / "items/sword_master_spawn_egg.json", {
        "model": {"type": "minecraft:model", "model": "wildercord:item/sword_master_spawn_egg"},
    })
