"""Validate the player guide and export ordinary Markdown for GitBook.

Hand-authored pages live in wiki/. tools/wiki.py refreshes the rune reference.
Run this after that generator; --check verifies the committed export without writing.
The export uses repository-hosted art instead of duplicating all game screenshots.
"""
import argparse
import html
import os
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
WIKI = ROOT / "wiki"
BOOK = ROOT / "gitbook"
RAW = "https://raw.githubusercontent.com/defnotean/wildercord/main/wiki"


def split_page(path):
    source = path.read_text(encoding="utf-8")
    match = re.match(r"\A---\s*\n(.*?)\n---\s*\n", source, re.S)
    if not match:
        raise ValueError(f"Missing frontmatter: {path}")
    metadata = {}
    for line in match[1].splitlines():
        key, sep, value = line.partition(":")
        if sep:
            metadata[key.strip()] = value.strip().strip('\"\'')
    return metadata, source[match.end():]


def url_for(path, metadata):
    if "permalink" in metadata:
        return metadata["permalink"]
    relative = path.relative_to(WIKI).with_suffix("").as_posix()
    if relative.endswith("/index"):
        relative = relative[:-6]
    return "/" + relative + "/"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    pages = {p: split_page(p) for p in sorted(WIKI.rglob("*.md"))}
    targets = {url_for(p, m): p for p, (m, _) in pages.items()}
    if len(targets) != len(pages):
        raise ValueError("Duplicate player-guide URLs")
    exports = {p: (Path("README.md") if p == WIKI / "index.md" else p.relative_to(WIKI)) for p in pages}
    output = {}

    for path, (metadata, body) in pages.items():
        # Check ordinary local Markdown links as well as the site's Liquid URLs.
        for reference in re.findall(r"\]\(([^)]+)\)", body):
            if "{{" in reference or reference.startswith(("http:", "https:", "#", "mailto:")):
                continue
            filename = reference.split("#", 1)[0].split("?", 1)[0]
            if filename and not (path.parent / filename).is_file():
                raise ValueError(f"Broken local link {reference} in {path}")
        def liquid_link(match):
            target, separator, fragment = match[1].partition("#")
            if target.startswith("/assets/"):
                asset = WIKI / target.lstrip("/")
                if not asset.is_file():
                    raise ValueError(f"Missing asset {target} in {path}")
                return RAW + target
            if target not in targets:
                raise ValueError(f"Unknown guide link {target} in {path}")
            return Path(os.path.relpath(exports[targets[target]], exports[path].parent)).as_posix() + (separator + fragment if separator else "")

        body = re.sub(r"\{\{\s*['\"]([^'\"]+)['\"]\s*\|\s*relative_url\s*\}\}", liquid_link, body)

        def recipe(match):
            options = dict(re.findall(r'(\w+)="([^"]*)"', match[1]))
            asset = f"/assets/recipes/{options['id']}.png"
            if not (WIKI / asset.lstrip("/")).is_file():
                raise ValueError(f"Missing recipe image {asset}")
            alt = options.get("alt", options.get("name", "Crafting recipe")).replace("[", "(").replace("]", ")")
            return f"![{alt}]({RAW}{asset})"

        body = re.sub(r"\{%\s*include recipe(?:-card)?\.html\s+(.*?)\s*%\}", recipe, body)
        body = re.sub(r"\{:[^}\n]*\}", "", body)
        body = re.sub(r"^1\. TOC\s*$", "", body, flags=re.M)
        # GitBook accepts Markdown images and ordinary HTML tables, but not theme classes.
        body = re.sub(r'<img\s+([^>]+)>', lambda m: image_markdown(m[1]), body)
        body = re.sub(r'\s+class="[^"]*"', "", body)
        if "{{" in body or "{%" in body:
            raise ValueError(f"Unconverted template in {path}")
        body = re.sub(r"\n{4,}", "\n\n\n", body).strip() + "\n"
        output[exports[path]] = body

    def order(path):
        try:
            return float(pages[path][0].get("nav_order", "999")), pages[path][0]["title"]
        except ValueError:
            return 999, pages[path][0]["title"]

    summary = ["# Summary", "", "<!-- Generated by tools/player_docs.py. Edit wiki/ source pages. -->", ""]
    visited = set()

    def add(path, depth=0):
        if path in visited:
            raise ValueError(f"Navigation cycle: {path}")
        visited.add(path)
        meta = pages[path][0]
        summary.append("  " * depth + f"* [{meta['title']}]({exports[path].as_posix()})")
        children = [p for p, (m, _) in pages.items() if m.get("parent") == meta["title"] and m.get("grand_parent", "") == meta.get("parent", "")]
        for child in sorted(children, key=order):
            add(child, depth + 1)

    for page in sorted((p for p, (m, _) in pages.items() if "parent" not in m), key=order):
        add(page)
    if len(visited) != len(pages):
        raise ValueError(f"Pages missing from navigation: {[str(p) for p in pages if p not in visited]}")
    output[Path("SUMMARY.md")] = "\n".join(summary) + "\n"

    failures = []
    for relative, content in output.items():
        target = BOOK / relative
        if args.check:
            if not target.is_file() or target.read_text(encoding="utf-8") != content:
                failures.append(relative.as_posix())
        else:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(content, encoding="utf-8", newline="\n")
    extra = {p.relative_to(BOOK) for p in BOOK.rglob("*.md")} - set(output)
    if extra:
        raise ValueError(f"Stale export pages: {sorted(str(p) for p in extra)}")
    if failures:
        raise ValueError(f"GitBook export is stale; run python tools/player_docs.py: {failures}")
    print(f"Player guide: {len(pages)} pages, all navigation/templated links/assets valid; GitBook {'checked' if args.check else 'exported'}.")


def image_markdown(attributes):
    fields = dict(re.findall(r'(\w+)="([^"]*)"', attributes))
    return f"![{html.unescape(fields.get('alt', '')).replace('[', '(').replace(']', ')')}]({fields['src']})"


if __name__ == "__main__":
    main()
