"""0.12 "Tempering": text for the re-measured hearts, the harder grind, tribulations and breakthrough rewards."""

LANG = {
    'monster.wildercord.variant.frost': 'Frost %s',
    'monster.wildercord.variant.ash': 'Ash %s',
    'monster.wildercord.alpha': 'Alpha %s',
 'screen.wildercord.breakthrough.scar': 'Tribulation Scar: one more heart of health for good (%s in all).',
 'message.wildercord.breakthrough.announce.circle': '%1$s has formed the %2$s Heart Circle.',
 'message.wildercord.breakthrough.announce.aura': '%1$s has broken through to %2$s.',
 'message.wildercord.boss.enraged': '%s is enraged: faster, harder, and shielded for a time.',
 'monster.wildercord.elite.splitting': 'Splitting %s',
 'message.wildercord.tribulation.scar': 'The tribulation leaves its mark: a Tribulation Scar, one more heart of health for good.',
 'screen.wildercord.breakthrough.title': 'Breakthrough',
 'screen.wildercord.breakthrough.gained': 'This circle adds +%1$s max mana, +%2$s mana regen per second and +%3$s%% spell power.',
 'screen.wildercord.breakthrough.unlocks': 'What it opens',
 'screen.wildercord.breakthrough.tribulation': 'Tribulation won: %1$s runes and %2$s Mana Crystals lie where it ended.',
 'screen.wildercord.breakthrough.vow': 'A vow to choose (see chat): %1$s (%2$s) or %3$s (%4$s).',
 'screen.wildercord.breakthrough.steady': 'A deeper well: more mana, faster regeneration and stronger spells.',
 'screen.wildercord.breakthrough.next_tribulation': 'The next circle is a Tribulation: %s waves of tempered Runebound will come for you when it forms. Prepare first.',
 'screen.wildercord.breakthrough.lesson.8': 'Lesson: Relay (see chat).',
 'screen.wildercord.breakthrough.lesson.10': 'Lesson: Tollgate (see chat).',
 'screen.wildercord.breakthrough.lesson.12': 'Lesson: Reweave (see chat).',
 'screen.wildercord.breakthrough.lesson.14': 'Lesson: Lifeline (see chat).',
 'screen.wildercord.breakthrough.lesson.16': 'Lesson: Excise (see chat).',
 'screen.wildercord.breakthrough.lesson.18': 'Lesson: Conduit (see chat).',
 'message.wildercord.retemper.dropped': 'Tempering: your heart has been measured again. Of your %1$s circles, %2$s hold under the new weight; the rest will form again as you condense more mana (%3$s for the next). Only spells that strike hostile creatures condense fully now.',
 'message.wildercord.retemper.kept': 'Tempering: your heart has been measured again and all %1$s circles hold. The next needs %3$s condensed mana. Only spells that strike hostile creatures condense fully now.',
 'message.wildercord.retemper.aura': 'Tempering: your aura has been measured again. It settles from %1$s back to %2$s; your experience is kept, and the breakthrough waits again once it reaches the new threshold.',
 'message.wildercord.tribulation.warn': 'The %1$s circle will not form quietly: when its meditation completes, a tribulation of %2$s waves comes for you. Find open ground, and be ready.',
 'message.wildercord.tribulation.begin': 'Tribulation of the %1$s circle: beat %2$s waves to form it. Stay within %3$s blocks; dying, fleeing or running out of time loses it (your condensed mana is kept).',
 'message.wildercord.tribulation.wave': 'Wave %1$s of %2$s',
 'message.wildercord.tribulation.last': 'Last wave (%1$s of %2$s): the Herald comes',
 'message.wildercord.tribulation.herald': 'A Herald of the Tribulation steps out of the storm',
 'message.wildercord.tribulation.breath': 'Wave %1$s of %2$s beaten. Breathe.',
 'message.wildercord.tribulation.rest': 'Your heart is still steadying from the last tribulation: %1$s seconds.',
 'message.wildercord.tribulation.won': 'The tribulation breaks. The %1$s circle is yours.',
 'message.wildercord.tribulation.failed.died': 'The tribulation of the %1$s circle is lost. Your heart needs %2$s minutes before it can be faced again.',
 'message.wildercord.tribulation.failed.fled': 'You left the circle of the tribulation, and the %1$s circle with it. Face it again in %2$s minutes.',
 'message.wildercord.tribulation.failed.time': 'The tribulation of the %1$s circle outlasted you. Face it again in %2$s minutes.',
 'message.wildercord.tribulation.failed.peaceful': 'The tribulation of the %1$s circle fades: the world is at peace.',
 'title.wildercord.tribulation': 'Tribulation',
 'title.wildercord.tribulation.sub': 'The %1$s circle must be won',
 'boss.wildercord.tribulation': 'Tribulation of the %1$s circle: wave %2$s of %3$s',
 'entity.wildercord.tribulation_herald': 'Herald of the Tribulation',
}


def write(g):
    pass
