"""More of the player wiki's generated reference pages, read from the game's own source so new content shows up by itself:

    wiki/runes/codex.md                  every rune by family and Codex category (spell/RuneCategories.java)
    wiki/progression/breathing-methods.md every breathing method and its five arts (aura/BreathingMethods.java, aura/arts/*)
    wiki/masters/techniques.md           every Sword Master and technique: strikes, shapes, answers, timing, damage, signatures and
                                         first-clear rewards (aura/world/MasterTechniques.java and the pack files it loads)

Called from tools/wiki.py (python tools/wiki.py). Pure Python: it reads the Java and the English lang file and never runs the game.
Anything it can't parse is skipped with a warning rather than guessed.
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
JAVA = ROOT / "src/main/java/dev/wildercord"
LANG = ROOT / "src/main/resources/assets/wildercord/lang/en_us.json"
WIKI = ROOT / "wiki"
MARK = "<!-- Generated by tools/wiki.py from the game's own data: edit that, not this page. -->"


def lang():
    try:
        return json.loads(LANG.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return {}


def titled(word):
    return word.replace("_", " ").strip().title()


def roman(n):
    out = ""
    for value, numeral in ((10, "X"), (9, "IX"), (5, "V"), (4, "IV"), (1, "I")):
        while n >= value:
            out += numeral
            n -= value
    return out


def seconds(ticks):
    s = ticks / 20
    return f"{s:.2f}".rstrip("0").rstrip(".") + " s"


def write(path, front, lines):
    path.parent.mkdir(parents=True, exist_ok=True)
    head = ["---"] + [f"{k}: {v}" for k, v in front.items()] + ["---", "", MARK, ""]
    path.write_text("\n".join(head + lines) + "\n", encoding="utf-8", newline="\n")


def cell(text):
    return str(text).replace("|", "\\|").replace("\n", " ")


# ------------------------------------------------------------------ Codex categories

FAMILIES = ["SHAPE", "EFFECT", "MODIFIER", "LINK", "KNOT"]


def read_categories():
    """RuneCategories.java: ({family: [categories in Codex order]}, {family: [(paths, category)]}, {family: default},
    {family: [(suffix, category)]}). Any list, case or suffix test someone adds is picked up."""
    src = (JAVA / "spell/RuneCategories.java").read_text(encoding="utf-8")
    order = {}
    for fam in FAMILIES:
        m = re.search(rf"\b{fam}\s*=\s*List\.of\((.*?)\);", src, re.S)
        order[fam] = re.findall(r'"(\w+)"', m.group(1)) if m else []
    for fam, cat in re.findall(r"RuneCategories\.add\(\s*RuneFamily\.(\w+)\s*,\s*\"(\w+)\"", _all_java()):
        if cat not in order.setdefault(fam, []):
            order[fam].append(cat)
    body = src[src.find("categoryFor("):]
    # Split the outer switch into one chunk per family.
    starts = [(m.start(), m.group(1)) for m in re.finditer(r"\bcase\s+(SHAPE|EFFECT|MODIFIER|LINK|KNOT)\s*->", body)]
    cases, defaults, suffixes = {}, {}, {}
    for i, (at, fam) in enumerate(starts):
        chunk = body[at:starts[i + 1][0] if i + 1 < len(starts) else len(body)]
        chunk = re.sub(r"//[^\n]*", "", chunk)
        cases[fam] = [(re.findall(r'"(\w+)"', paths), cat)
                      for paths, cat in re.findall(r'case\s+((?:"\w+"\s*,\s*)*"\w+")\s*->\s*"(\w+)"\s*;', chunk, re.S)]
        d = re.search(r'default\s*->\s*"(\w+)"', chunk)
        direct = re.match(r'case\s+\w+\s*->\s*"(\w+)"', chunk)
        defaults[fam] = d.group(1) if d else (direct.group(1) if direct else "")
        suffixes[fam] = re.findall(r'path\.endsWith\("(\w+)"\)\s*\?\s*"(\w+)"', chunk)
    return order, cases, defaults, suffixes


def _all_java():
    return "\n".join(p.read_text(encoding="utf-8", errors="replace") for p in JAVA.rglob("*.java"))


def category(path, family, cases, defaults, suffixes):
    fam = family.upper()
    for suffix, cat in suffixes.get(fam, []):
        if path.endswith(suffix):
            return cat
    for paths, cat in cases.get(fam, []):
        if path in paths:
            return cat
    return defaults.get(fam, "")


CATEGORY_BLURB = {
    ("shape", "personal"): "On you or around you.",
    ("shape", "direct"): "Straight from you to what you aim at, with no flight time.",
    ("shape", "projectile"): "Something that flies and can miss.",
    ("shape", "area"): "Everything in a space at once.",
    ("shape", "lingering"): "Waits on the ground or in the air and works over time.",
}


def codex_page(runes, link_of):
    order, cases, defaults, suffixes = read_categories()
    words = lang()
    lines = ["# Runes by Codex category", "",
             "The Codex in your Cord screen sorts each rune family into categories by what the rune is *for*. "
             "This page uses the same sorting, so you can find, say, every World effect or every Condition link in one place. "
             "Each name links to the rune's full entry.", ""]
    family_title = {"shape": "Shapes", "effect": "Effects", "modifier": "Modifiers", "link": "Links"}
    total = 0
    for family in ("shape", "effect", "modifier", "link"):
        rs = [r for r in runes if r["family"] == family]
        if not rs:
            continue
        groups = {}
        for r in rs:
            groups.setdefault(category(r["path"], family, cases, defaults, suffixes) or "other", []).append(r)
        known = order.get(family.upper(), [])
        cats = [c for c in known if c in groups] + sorted(c for c in groups if c not in known)
        lines += [f"## {family_title[family]}", ""]
        lines += ["| Category | Runes |", "|---|---|"]
        for cat in cats:
            label = words.get(f"category.wildercord.{family}.{cat}", titled(cat))
            lines.append(f"| [{cell(label)}](#{family}-{cat}) | {len(groups[cat])} |")
        lines.append("")
        for cat in cats:
            label = words.get(f"category.wildercord.{family}.{cat}", titled(cat))
            lines += [f"### {label} {family_title[family].lower()}", f"{{: #{family}-{cat}}}", ""]
            if CATEGORY_BLURB.get((family, cat)):
                lines += [CATEGORY_BLURB[(family, cat)], ""]
            items = []
            for r in sorted(groups[cat], key=lambda r: (r["tier"], r["name"])):
                extra = f", {r['element'].title()}" if r.get("element") else ""
                items.append(f"- {link_of(r['path'])} (Tier {roman(r['tier'])}{extra})")
            lines += items + [""]
            total += len(groups[cat])
    lines.insert(4, f"{total} runes in all.")
    lines.insert(5, "")
    write(WIKI / "runes/codex.md", {"title": "By Codex Category", "parent": "Runes", "nav_order": 8}, lines)
    return total


# ------------------------------------------------------------------ breathing methods and arts

SLOTS = ["FIRST", "SECOND", "THIRD", "FOURTH", "FINAL"]


def _string_consts():
    """{class name: {CONST: "value"}} for every `static final String X = "y"` in the source, so a constant id resolves."""
    out = {}
    for p in JAVA.rglob("*.java"):
        src = p.read_text(encoding="utf-8", errors="replace")
        out[p.stem] = dict(re.findall(r'static\s+final\s+String\s+(\w+)\s*=\s*"([\w:]+)"', src))
    return out


def _resolve(ref, src, here, consts):
    """A string literal, a Class.CONST, or a CONST from this file or a static import, as its value; None if unknown."""
    ref = ref.strip()
    if ref.startswith('"'):
        return ref.strip('"')
    if "." in ref:
        cls, name = ref.rsplit(".", 1)
        return consts.get(cls.rsplit(".", 1)[-1], {}).get(name)
    if ref in consts.get(here, {}):
        return consts[here][ref]
    for cls in re.findall(r"import\s+static\s+[\w.]*?\.(\w+)\.(?:\*|" + re.escape(ref) + r")\s*;", src):
        if ref in consts.get(cls, {}):
            return consts[cls][ref]
    return None


def read_methods():
    """Every `new BreathingMethod(id, "element", ...)` in the source, in file order (BreathingMethods.java first). The id may be a
    literal or a constant (Echo, Dawn and Venom use MethodsBArtRules' ids and register outside BUILT_IN)."""
    consts = _string_consts()
    files = [JAVA / "aura/BreathingMethods.java"] + sorted(p for p in JAVA.rglob("*.java") if p.name != "BreathingMethods.java")
    seen, methods = set(), []
    for f in files:
        if not f.exists():
            continue
        src = f.read_text(encoding="utf-8", errors="replace")
        for m in re.finditer(r'new\s+BreathingMethod\(\s*("\w+"|[\w.]+)\s*,\s*"(\w+)"', src):
            mid = _resolve(m.group(1), src, f.stem, consts)
            if mid is None:
                print(f"wiki_reference: skipped a breathing method whose id it couldn't read: {m.group(1)} in {f.name}")
                continue
            if mid not in seen:
                seen.add(mid)
                methods.append({"id": mid, "element": m.group(2)})
    return methods


def read_arts():
    """{method id: [(slot, art id)]} from every *Arts.java that declares METHOD and MethodArts.art(ArtSlot.X, CONST, ...)."""
    consts = _string_consts()
    arts = {}
    for f in sorted((JAVA / "aura").rglob("*Arts.java")):
        src = f.read_text(encoding="utf-8", errors="replace")
        method = re.search(r'\bMETHOD\s*=\s*("\w+"|[\w.]+)\s*;', src)
        if not method:
            continue
        mid = _resolve(method.group(1), src, f.stem, consts)
        if mid is None:
            print(f"wiki_reference: skipped {f.name}: couldn't read its METHOD")
            continue
        found = []
        for slot, ref in re.findall(r"MethodArts\.art\(\s*(?:AuraApi\.)?ArtSlot\.(\w+)\s*,\s*(\w+|\"[\w:]+\")", src):
            art = _resolve(ref, src, f.stem, consts)
            if art:
                found.append((slot, art))
        arts.setdefault(mid, []).extend(found)
    return arts


def read_slot_rules():
    src = (JAVA / "aura/ArtRules.java").read_text(encoding="utf-8")
    cost = re.search(r"SLOT_COST\s*=\s*\{([^}]*)\}", src)
    cool = re.search(r"SLOT_COOLDOWN\s*=\s*\{([^}]*)\}", src)
    costs = [float(x) for x in cost.group(1).split(",")] if cost else []
    cools = [int(x) for x in cool.group(1).split(",")] if cool else []
    api = (JAVA / "api/AuraApi.java").read_text(encoding="utf-8")
    stages = dict(re.findall(r"\b(FIRST|SECOND|THIRD|FOURTH|FINAL)\(\"[^\"]*\",\s*AuraRules\.(\w+)\)", api))
    strings = dict(re.findall(r"\b(FIRST|SECOND|THIRD|FOURTH|FINAL)\(\"([^\"]*)\"", api))
    return costs, cools, stages, strings


STRING_WORDS = {"swing swing low": "swing, swing, low swing", "leap low": "leaping swing, then a low swing",
                "counter": "your first swing after a perfect Aura Guard", "step": "your first swing after an Aura Step",
                "full full full low": "three full swings, then a low swing"}


def methods_page():
    words = lang()
    methods = read_methods()
    arts = read_arts()
    costs, cools, stages, strings = read_slot_rules()
    lines = ["# Breathing methods", "",
             "A **breathing method** is the element your Aura takes. Each one colours your Aura, adds its own touch to your blows, "
             "and gives you five **arts**: special cuts you play by swinging a set pattern with your sword. "
             f"There are {len(methods)} methods. For how to choose and change one, see [Aura]({{{{ '/progression/aura/' | relative_url }}}}).", "",
             "## How arts unlock", "",
             "Every method's arts open at the same Aura stages and use the same swing patterns:", "",
             "| Art | Opens at | Play it with | Aura cost | Rest |", "|---|---|---|---|---|"]
    for i, slot in enumerate(SLOTS):
        stage = words.get(f"aura.wildercord.stage.{stages.get(slot, '').lower()}", titled(stages.get(slot, "")))
        pattern = STRING_WORDS.get(strings.get(slot, ""), strings.get(slot, ""))
        name = words.get(f"aura.wildercord.art.{slot.lower()}_art", titled(slot.lower() + " art"))
        cost = f"{costs[i]:g}" if i < len(costs) else ""
        rest = seconds(cools[i]) if i < len(cools) else ""
        lines.append(f"| {name} | {stage} | {pattern} | {cost} | {rest} |")
    lines += ["", "Some arts set their own cost or rest; the Aura page in game always shows the real numbers.", ""]
    lines += ["| Method | Element |", "|---|---|"]
    for m in methods:
        name = words.get(f"aura.wildercord.method.{m['id']}", titled(m["id"]))
        lines.append(f"| [{name}](#{m['id']}) | {m['element'].title()} |")
    lines.append("")
    for m in methods:
        name = words.get(f"aura.wildercord.method.{m['id']}", titled(m["id"]))
        lines += [f"## {name}", f"{{: #{m['id']}}}", "", f"*{m['element'].title()}*", ""]
        lore = words.get(f"aura.wildercord.method.{m['id']}.lore")
        flavour = words.get(f"aura.wildercord.method.{m['id']}.flavour")
        if lore:
            lines += [f"> {lore}", ""]
        if flavour:
            lines += [flavour, ""]
        own = arts.get(m["id"], [])
        if own:
            lines += ["| Art | Name | What it does |", "|---|---|---|"]
            for slot, art in sorted(own, key=lambda a: SLOTS.index(a[0]) if a[0] in SLOTS else 9):
                key = art.replace(":", ".")
                art_name = words.get(f"aura.wildercord.art.{key}", titled(art.split(":")[-1]))
                desc = words.get(f"aura.wildercord.art.{key}.desc", "")
                slot_name = words.get(f"aura.wildercord.art.{slot.lower()}_art", titled(slot.lower()))
                lines.append(f"| {slot_name} | **{cell(art_name)}** | {cell(desc)} |")
            lines.append("")
        else:
            lines += ["This method plays the five common arts.", ""]
    write(WIKI / "progression/breathing-methods.md",
          {"title": "Breathing Methods", "parent": "Growing Stronger", "nav_order": 2.25}, lines)
    return len(methods)


# ------------------------------------------------------------------ Sword Master techniques

ANSWER = {"ARC": "Back off or guard", "ARC_LOW": "Jump", "ARC_HIGH": "Crouch", "LANE": "Sidestep", "CIRCLE": "Leave the circle"}
STRIKE_NAME = {"SWEEP": "sweeping cut", "THRUST": "thrust", "RISING": "rising cut", "DROP": "dropping cut", "LOW": "low sweep",
               "PLUNGE": "plunge", "DRIVE": "driving cut", "REPLY": "reply cut", "CLEAVE": "cleave", "WHIRL": "whirl",
               "FALLING": "falling cut", "HIGH": "high sweep", "LUNGE": "lunge", "UPPER": "upward cut", "PALM": "palm strike"}
SHAPE_WORD = {"ARC": "broad cut", "ARC_LOW": "low sweep", "ARC_HIGH": "high sweep", "LANE": "straight line", "CIRCLE": "spinning circle"}


def _num(expr):
    return float(re.sub(r"[^\d.\-]", "", expr) or 0)


def _src(rel):
    return (JAVA / rel).read_text(encoding="utf-8")


def _ints(src):
    """Every `static final int A = 1, B = 2;` constant in a file."""
    out = {}
    for decl in re.findall(r"static\s+final\s+int\s+([^;]*);", src):
        for name, value in re.findall(r"\b(\w+)\s*=\s*(-?\d+)\b", decl):
            out[name] = int(value)
    return out


def _const(src, name, file):
    m = re.search(rf"\b{name}\s*=\s*([\d.]+)", src)
    if not m:
        raise ValueError(f"wiki_reference: {name} not found in {file}")
    return float(m.group(1))


def _body(src, signature):
    """The body of the first method whose declaration matches `signature` (a regex), up to its closing tab-brace."""
    m = re.search(signature + r"[^{]*\{(.*?)\n\t\}", src, re.S)
    return m.group(1) if m else ""


def read_tables():
    """[(school constant, table text, pack)] in id order: the base three, masters-a, masters-b, methods-a, then methods-b's reserved ids."""
    mt = _src("aura/world/MasterTechniques.java")
    out = [(s, t, "base") for s, t in re.findall(r'school\(\s*MastersRules\.(\w+)\s*,\s*"""(.*?)"""\s*\)', mt, re.S)]
    em = _src("aura/world/ElementalMasters.java")
    order = re.search(r"SCHOOL_IDS\s*=\s*List\.of\(([^)]*)\)", em).group(1)
    em_tables = dict(re.findall(r'case\s+(\w+)\s*->\s*"""(.*?)"""', _body(em, r"static String techniques\(int school\)"), re.S))
    out += [(s.strip(), em_tables[s.strip()], "masters-a") for s in order.split(",") if s.strip() in em_tables]
    pb = _src("aura/world/MastersPackB.java")
    out += [(s, t, "masters-b") for s, t in re.findall(r'table\.add\(\s*(\w+)\s*,\s*"""(.*?)"""\s*\)', pb, re.S)]
    ma = _src("aura/world/MethodsAMasters.java")
    ma_tables = dict(re.findall(r'String\s+(\w+_TABLE)\s*=\s*"""(.*?)"""', ma, re.S))
    out += [(s, ma_tables[t], "methods-a") for s, t in re.findall(r"table\.add\(\s*(\w+)\s*,\s*(\w+_TABLE)\s*\)", ma) if t in ma_tables]
    mb = _src("aura/world/MethodsBMasters.java")
    mb_tables = dict(re.findall(r'String\s+(\w+_TABLE)\s*=\s*"""(.*?)"""', mb, re.S))
    out += [(s, mb_tables[t], "methods-b") for s, t in
            re.findall(r"school\(\s*MethodsBMasters\.(\w+)\s*,\s*MethodsBMasters\.(\w+_TABLE)", mt) if t in mb_tables]
    return out


def read_pack_timing():
    """How each pack re-times what the base formula authors: read from the pack's own tell()/recovery() and constants."""
    mt = _src("aura/world/MasterTechniques.java")
    em = _src("aura/world/ElementalMasters.java")
    e = _ints(em)
    tell_body = _body(em, r"static int tell\(boolean heavy")
    heavy = re.search(r"heavy\s*\?\s*(\d+)\s*:\s*0", tell_body)
    turn = re.search(r"spin\s*\|\|\s*step\s*\?\s*(\d+)\s*:\s*0", tell_body)
    extra = re.search(r"Math\.min\((\d+),\s*count\s*-\s*1\)", em)
    if not (heavy and turn and extra) or "ElementalMasters.tell(" not in mt:
        print("wiki_reference: masters-a's tell rule changed shape; its times may be off")
    timing = {"masters-a": {"kind": "fixed", "min": e["MIN_TELL"], "max": e["MAX_TELL"], "heavy": int(heavy.group(1)) if heavy else 1,
                            "turn": int(turn.group(1)) if turn else 1, "rec": e["MIN_RECOVERY"],
                            "rec_extra": int(extra.group(1)) if extra else 2}}
    for pack, rel, hook in (("masters-b", "aura/world/MastersPackB.java", "MastersPackB"),
                            ("methods-a", "aura/world/MethodsAMasters.java", "MethodsAMasters")):
        src = _src(rel)
        c = _ints(src)
        chain = re.search(r"authored\s*\+\s*\(index\s*==\s*0\s*\?\s*(\d+)\s*:\s*(\d+)\)", src)
        if not chain or f"{hook}.tell(" not in mt:
            print(f"wiki_reference: {pack}'s tell rule changed shape; its times may be off")
        timing[pack] = {"kind": "clamp", "min": c["MIN_TELL"], "max": c["MAX_TELL"], "first": int(chain.group(1)) if chain else 0,
                        "follow": int(chain.group(2)) if chain else 0, "rec_min": c["MIN_RECOVERY"], "rec_max": c["MAX_RECOVERY"]}
    if "MethodsBMasters.tell(" in mt or "MethodsBMasters.recovery(" in mt:
        print("wiki_reference: methods-b now re-times its techniques; teach read_pack_timing() its rule")
    return timing


def read_signatures(words):
    """({school constant: [signature names]}, [methods-b signature technique keys]): single-school moves in MasterMoveCatalog,
    plus the techniques methods-b names as signatures."""
    cat = _src("aura/world/MasterMoveCatalog.java")
    sig = {}
    for move, school in re.findall(r"MastersRules\.Move\.(\w+)\s*,\s*Set\.of\(\s*\w+\.(\w+)\s*\)", cat):
        sig.setdefault(school, []).append(words.get(f"boss.wildercord.master.{move.lower()}", titled(move)))
    mb = _src("aura/world/MethodsBMasters.java")
    block = re.search(r"SIGNATURES\s*=\s*Map\.of\((.*?)\);", mb, re.S)
    keys = re.findall(r'"(\w+)"\s*,\s*MethodsBSignatureRules\.Signature\.\w+', block.group(1)) if block else []
    return sig, keys


def read_rewards(words):
    """{school constant: technique-part name} from MasterVictoryRules.reward and the pack reward() it hands off to."""
    tr = dict(re.findall(r'static\s+final\s+String\s+(\w+)\s*=\s*"(\w+)"', _src("aura/TechniqueRules.java")))
    out = {}
    for rel in ("aura/world/ElementalMasters.java", "aura/world/MethodsAMasters.java", "aura/world/MethodsBMasters.java",
                "aura/world/MasterVictoryRules.java"):
        body = _body(_src(rel), r"static String reward\(int school\)")
        for labels, const in re.findall(r"case\s+([\w.,\s]+?)\s*->\s*[\w.]*TechniqueRules\.(\w+)", body):
            part = tr.get(const, const.lower())
            for label in labels.split(","):
                out.setdefault(label.strip().rsplit(".", 1)[-1], words.get(f"aura.wildercord.technique_part.{part}", titled(part)))
    return out


def read_techniques():
    mt = _src("aura/world/MasterTechniques.java")
    consts = {k: int(v) for k, v in re.findall(r"\b(\w+)\s*=\s*(-?\d+)", re.search(r"FIRST_TELL[^;]*;", mt).group(0))}
    first, follow, least = consts.get("FIRST_TELL", 12), consts.get("FOLLOW_TELL", 8), consts.get("MIN_TELL", 5)
    max_share = _num(re.search(r"MAX_SHARE\s*=\s*([\d.]+)", mt).group(1))
    prims = {}
    for name, shape, reach, width, damage in re.findall(
            r'primitive\("(\w+)",.*?Shape\.(\w+),\s*([\d.]+),\s*([\d.]+),\s*([\d.]+)\)\s*;', mt, re.S):
        prims[name] = {"shape": shape, "reach": float(reach), "width": float(width), "damage": float(damage)}
    tempo_body = re.search(r"double tempo\(int school\)\s*\{(.*?)\}", mt, re.S).group(1)
    tempo = {k: float(v) for k, v in re.findall(r"MastersRules\.(\w+)\s*\?\s*([\d.]+)", tempo_body)}
    tempo_default = float(re.findall(r":\s*([\d.]+)\s*;", tempo_body)[-1]) if re.findall(r":\s*([\d.]+)\s*;", tempo_body) else 1.0
    rec_m = re.search(r"int recovery = (.*?);", mt, re.S)
    rec_adj = {k: int(v) for k, v in re.findall(r"MastersRules\.(\w+)\s*\?\s*(-?\d+)", rec_m.group(1))} if rec_m else {}
    rules = _src("aura/world/MastersRules.java")
    attack_cost = _const(rules, "ATTACK_COST", "MastersRules")
    hit = _const(rules, "TECHNIQUE_DAMAGE", "MastersRules")
    stone_m = re.search(r"discipline\(discipline\)\s*==\s*(\w+)\s*\?\s*([\d.]+)", _body(rules, r"static double damage\(int count"))
    heavy_school, heavy_mult = (stone_m.group(1), float(stone_m.group(2))) if stone_m else ("STONE", 1.0)
    # Methods-b Masters fight on a built-in school's footing (SwordMaster sets it as their discipline), which sets their damage.
    mb = _src("aura/world/MethodsBMasters.java")
    base_body = _body(mb, r"static int base\(int school\)")
    footing = dict(re.findall(r"case\s+(\w+)\s*->\s*MastersRules\.(\w+)", base_body))
    default_m = re.search(r"default\s*->\s*MastersRules\.(\w+)", base_body)
    footing_default = default_m.group(1) if default_m else "EMBER"
    timing = read_pack_timing()
    out = []
    for school, table, pack in read_tables():
        discipline = footing.get(school, footing_default) if pack == "methods-b" else school
        mult = heavy_mult if discipline == heavy_school else 1.0
        t = timing.get(pack)
        for line in table.strip().splitlines():
            parts = line.split()
            if len(parts) < 2 or len(parts) > 5:
                continue
            count = len(parts) - 1
            share = {1: .9, 2: .6, 3: .5}.get(count, .42)
            strikes, at, last_heavy, ok = [], 0, False, True
            for i, token in enumerate(parts[1:]):
                flags = re.match(r"[~@*!^]*", token).group(0)
                prim = prims.get(token[len(flags):])
                if prim is None:
                    ok = False
                    break
                spin = "@" in flags or token[len(flags):] == "WHIRL"
                heavy, quick, step = "!" in flags, "*" in flags, 2.0 * flags.count("^")
                tell = (first if i == 0 else follow) + (4 if heavy else 0) - (3 if quick else 0) + (2 if step else 0) + (2 if spin else 0)
                tell = max(least, int(round(tell * tempo.get(school, tempo_default))))
                if t and t["kind"] == "fixed":
                    tell = max(t["min"], min(t["max"], t["min"] + (t["heavy"] if heavy else 0) + (t["turn"] if spin or step else 0)))
                elif t and t["kind"] == "clamp":
                    tell = max(t["min"], min(t["max"], tell + (t["first"] if i == 0 else t["follow"])))
                shape = "CIRCLE" if spin else prim["shape"]
                reach = min(prim["reach"], 3.75) if spin else prim["reach"]
                at += tell
                strikes.append({"name": token[len(flags):], "shape": shape, "reach": reach, "step": step, "heavy": heavy, "quick": quick,
                                "mirrored": "~" in flags, "tell": tell, "at": at,
                                "damage": share * prim["damage"] * (1.3 if heavy else 1) * (.85 if quick else 1)})
                last_heavy = heavy
            if not ok:
                print(f"wiki_reference: skipped technique line it couldn't read: {line.strip()}")
                continue
            total = sum(s["damage"] for s in strikes)
            if total > max_share:
                for s in strikes:
                    s["damage"] *= max_share / total
            recovery = 12 + 3 * (count - 1) + (4 if last_heavy else 0) + rec_adj.get(school, 0)
            if t and t["kind"] == "fixed":
                recovery = t["rec"] + max(0, min(t["rec_extra"], count - 1))
            elif t and t["kind"] == "clamp":
                recovery = max(t["rec_min"], min(t["rec_max"], recovery))
            out.append({"key": parts[0], "school": school, "pack": pack, "strikes": strikes, "recovery": recovery,
                        "cost": attack_cost + 4 * (count - 1), "base_damage": sum(s["damage"] for s in strikes) * hit * mult})
    return out, {"first": first, "tempo": tempo, "tempo_default": tempo_default, "footing": footing, "footing_default": footing_default,
                 "hit": hit, "heavy_school": heavy_school, "heavy_mult": heavy_mult, "max_share": max_share}


def strike_words(s):
    bits = []
    if s["heavy"]:
        bits.append("heavy")
    if s["quick"]:
        bits.append("quick")
    if s["shape"] == "CIRCLE" and s["name"] != "WHIRL":
        bits.append("spinning")
    bits.append(STRIKE_NAME.get(s["name"], s["name"].lower().replace("_", " ")))
    text = " ".join(bits)
    if s["step"]:
        text += f" with a {s['step']:g}-block step in"
    return text[0].upper() + text[1:]


def read_signature_effects():
    """{methods-b signature (TOLL...): effect name} from what MethodsBMasters.afflict leaves on a player it caught."""
    body = _body(_src("aura/world/MethodsBMasters.java"), r"static void afflict\(")
    return {sig: titled(effect) for sig, effect in re.findall(r"case\s+(\w+)\s*->\s*player\.addEffect\(new MobEffectInstance\(MobEffects\.(\w+)", body)}


def _span(values):
    lo, hi = min(values), max(values)
    return seconds(lo) if lo == hi else f"{seconds(lo)[:-2]} to {seconds(hi)}"


def techniques_page():
    words = lang()
    techniques, info = read_techniques()
    signatures, mb_keys = read_signatures(words)
    mb_sig = dict(re.findall(r'"(\w+)"\s*,\s*MethodsBSignatureRules\.Signature\.(\w+)', _src("aura/world/MethodsBMasters.java")))
    effects = read_signature_effects()
    rewards = read_rewards(words)
    schools = []
    for t in techniques:
        if t["school"] not in schools:
            schools.append(t["school"])
    for t in techniques:
        if t["key"] in mb_keys:
            signatures.setdefault(t["school"], []).append(words.get(f"boss.wildercord.master.technique.{t['key']}", titled(t["key"])))
    school_name = {s: words.get(f"master.wildercord.school.{s.lower()}", titled(s)) for s in schools}
    method_link = {s: f"[{words.get(f'aura.wildercord.method.{s.lower()}', titled(s))}]({{{{ '/progression/breathing-methods/' | relative_url }}}}#{s.lower()})"
                   for s in schools}
    lines = ["# Master techniques", "",
             f"There are {len(schools)} Sword Masters, one for each breathing method. Each one fights with its own set of named "
             f"techniques: {len(techniques)} in all. A technique is one to four strikes. "
             "Each strike has a **wind-up** (the Master's tell) and a **shape**, and the shape tells you how to get out of the way.", "",
             "## The Masters", "",
             "| Master | Breathing method | Signature moves | First clear teaches | Techniques |", "|---|---|---|---|---|"]
    for s in schools:
        count = sum(1 for t in techniques if t["school"] == s)
        sig = ", ".join(signatures.get(s, [])) or "None"
        reward = f"[{rewards[s]}]({{{{ '/progression/techniques/' | relative_url }}}})" if s in rewards else "Nothing new"
        lines.append(f"| [{school_name[s]}](#{s.lower()}) | {method_link[s]} | {cell(sig)} | {reward} | {count} |")
    lines += ["",
              "Your **first clear** of a Master teaches you its technique part, once. Several Masters teach the same part "
              "(for example Bind), so a later clear of another one may only record the win.", "",
              "## Reading a strike", "",
              "| Shape | What you see | Your answer |", "|---|---|---|",
              "| Broad cut | A wide sweeping cut in front | " + ANSWER["ARC"] + " (step out of reach) |",
              "| Low sweep | The blade sweeps along the ground | " + ANSWER["ARC_LOW"] + " |",
              "| High sweep | The blade cuts at head height | " + ANSWER["ARC_HIGH"] + " |",
              "| Line | A thrust, lunge, cleave or other straight cut along one narrow lane | " + ANSWER["LANE"] + " out of the lane |",
              "| Circle | A whirl, or any strike thrown spinning | " + ANSWER["CIRCLE"] + " (step out of the radius) |", "",
              "In the tables below every strike is named, and the **Answers** column gives the answer for each strike in order.", "",
              "**Heavy** strikes wind up longer and hit harder. **Quick** strikes wind up faster and hit lighter. "
              "A strike *with a step in* closes distance first, so standing just out of reach is not enough. "
              "After the last strike the Master needs a moment to **recover**: that is your opening to hit back.", "",
              "**Pace.** Each school has its own pace, shown under its name: how long each wind-up takes, and how long the Master stays open after.", "",
              f"**Base damage** is the whole technique if every strike lands, in health points (2 points is one heart), "
              f"before your defence and elemental match-ups. One technique can never deal more than {info['max_share']:g} times "
              f"a single hit. Masters on Stone's footing hit {round((info['heavy_mult'] - 1) * 100):g}% harder.", "",
              "Jump to a school: " + " · ".join(f"[{school_name[s]}](#{s.lower()})" for s in schools), ""]
    for s in schools:
        ts = [t for t in techniques if t["school"] == s]
        tells = [x["tell"] for t in ts for x in t["strikes"]]
        recs = [t["recovery"] for t in ts]
        lines += [f"## {school_name[s]} Master", f"{{: #{s.lower()}}}", ""]
        about = f"{len(ts)} techniques. Breathing method: {method_link[s]}."
        if (WIKI / f"masters/{s.lower()}.md").exists():
            about += f" More about this school: [{school_name[s]} Master]({{{{ '/masters/{s.lower()}/' | relative_url }}}})."
        lines += [about, ""]
        lines += [f"- **Pace:** each wind-up takes {_span(tells)}. After a technique it stays open for {_span(recs)}."]
        if signatures.get(s):
            lines.append(f"- **Signature:** {', '.join(signatures[s])}.")
        if s in rewards:
            lines.append(f"- **First clear teaches:** {rewards[s]}.")
        lesson = words.get(f"message.wildercord.master.{s.lower()}_lesson") or words.get(f"message.wildercord.master.methods_b_{s.lower()}_lesson")
        lines.append("")
        if lesson:
            lines += [f"> {lesson}", ""]
        lines += ["| Technique | Strikes, in order | Answers | Last hit lands | Recovery | Base damage |", "|---|---|---|---|---|---|"]
        for t in ts:
            name = words.get(f"boss.wildercord.master.technique.{t['key']}", titled(t["key"]))
            strikes = " → ".join(strike_words(x) for x in t["strikes"])
            answers = " → ".join(ANSWER.get(x["shape"], "?") for x in t["strikes"])
            sig = mb_sig.get(t["key"])
            if sig:
                name += " (signature)"
                hint = words.get(f"message.wildercord.master.methods_b.{sig.lower()}_hint", "")
                answers = hint.rstrip("!.") + (f". If it catches you: {effects[sig]}" if sig in effects else "")
            lines.append(f"| **{cell(name)}** | {cell(strikes)} | {cell(answers)} | {seconds(t['strikes'][-1]['at'])} | "
                         f"{seconds(t['recovery'])} | {t['base_damage']:.1f} |")
        lines.append("")
    write(WIKI / "masters/techniques.md", {"title": "Master Techniques", "parent": "Sword Masters", "nav_order": 5}, lines)
    return len(techniques)


def main(runes, link_of):
    n = codex_page(runes, link_of)
    m = methods_page()
    t = techniques_page()
    print(f"{n} runes by Codex category, {m} breathing methods, {t} Master techniques written to the wiki")
